#
# Makefile rules for compiling examples.
#

vpath %.f90 $(VPATHS)
vpath %.c   $(VPATHS)
vpath %.f   $(VPATHS)

$(EXE): $(OBJ)
ifeq ($(MKVERBOSE),TRUE)
	$(FC) $(FFLAGS) $^ $(OUTPUT_OPTION) $(LDFLAGS)
else
	@echo "Linking..."
	@$(FC) $(FFLAGS) $^ $(OUTPUT_OPTION) $(LDFLAGS)
endif

build/%.o build/%.mod: %.f90
	@mkdir -p build
	@mkdir -p include
ifeq ($(MKVERBOSE),TRUE)
	$(FC) $(FFLAGS) -c $< $(OUTPUT_OPTION)
else
	@echo "Building $<..."
	@$(FC) $(FFLAGS) -c $< $(OUTPUT_OPTION)
endif

build/%.o: %.c
	@mkdir -p build
	@mkdir -p include

ifeq ($(MKVERBOSE),TRUE)
	$(CC) $(CFLAGS) -c $< $(OUTPUT_OPTION)
else
	@echo "Building $<..."
	@$(CC) $(CFLAGS) -c $< $(OUTPUT_OPTION)
endif

build/%.o: %.f
	@mkdir -p build
	@mkdir -p include
ifeq ($(MKVERBOSE),TRUE)
	$(FC) $(F77FLAGS) -c $< $(OUTPUT_OPTION)
else
	@echo "Building $<..."
	@$(FC) $(F77FLAGS) -c $< $(OUTPUT_OPTION)
endif

.PHONY: clean depend

clean:
	find . -name build | xargs rm -rf
	find . -name '*.exe' | xargs rm -f
	\rm -f fort.* *.slog2 *.edf *.trc gmon.out
	\rm include/*.mod


#  We can use this to build a new dependency file if makedepf90 is installed  type "make depend"
#depend $(LIBPFASST)/.depend:
#	makedepf90 -b ./build -o foo $(FSRC) > .depend

#
# LIBPFASST dependencies
#
include $(LIBPFASST)/.depend

#  Outdated dependencies
#ifdef NOMPI
#  build/pfasst.o: build/pf_parallel.o build/pf_pfasst.o  build/pf_imexQ.o build/pf_imexQ_oc.o build/pf_rks#tepper.o 
#else
#build/pfasst.o:         build/pf_parallel.o  build/pf_pfasst.o build/pf_mpi.o build/pf_imexQ.o build/pf_rk#stepper.o 
#endif

#build/pf_amisdc.o:      build/pf_timer.o build/pf_explicit.o build/pf_implicit.o build/pf_utils.o
#build/pf_amisdcQ.o:      build/pf_timer.o build/pf_explicit.o build/pf_implicit.o build/pf_utils.o























