#
# Makefile rules for compiling examples.
#

vpath %.f90 $(VPATHS)
vpath %.c   $(VPATHS)
vpath %.f   $(VPATHS)

$(EXE): $(OBJ)
ifdef MKVERBOSE
	$(FC) $(FFLAGS) $^ $(OUTPUT_OPTION) $(LDFLAGS)
else
	@echo "Linking..."
	@$(FC) $(FFLAGS) $^ $(OUTPUT_OPTION) $(LDFLAGS)
endif

build/%.o: %.f90
	@mkdir -p build
ifdef MKVERBOSE
	$(FC) $(FFLAGS) -c $< $(OUTPUT_OPTION)
else
	@echo "Building $<..."
	@$(FC) $(FFLAGS) -c $< $(OUTPUT_OPTION)
endif

build/%.o: %.c
	@mkdir -p build
ifdef MKVERBOSE
	$(CC) $(CFLAGS) -c $< $(OUTPUT_OPTION)
else
	@echo "Building $<..."
	@$(CC) $(CFLAGS) -c $< $(OUTPUT_OPTION)
endif

build/%.o: %.f
	@mkdir -p build
ifdef MKVERBOSE
	$(FC) $(F77FLAGS) -c $< $(OUTPUT_OPTION)
else
	@echo "Building $<..."
	@$(FC) $(F77FLAGS) -c $< $(OUTPUT_OPTION)
endif

.PHONY: clean

clean:
	find . -name build | xargs rm -rf
	find . -name '*.exe' | xargs rm -f
	rm -f fort.* *.slog2 *.edf *.trc gmon.out

#
# LIBPFASST dependencies
#

build/pf_timer.o:       build/pf_dtype.o
build/pf_ndarray.o:     build/pf_dtype.o
build/pf_utils.o:       build/pf_timer.o
build/pf_explicit.o:    build/pf_timer.o build/pf_utils.o
build/pf_hooks.o:       build/pf_timer.o
build/pf_hooks.o:       build/pf_timer.o
build/pf_implicit.o:    build/pf_timer.o build/pf_utils.o
build/pf_mpi.o:         build/pf_timer.o
build/pf_logger.o:      build/pf_hooks.o
build/pf_imex.o:        build/pf_timer.o build/pf_explicit.o build/pf_implicit.o build/pf_utils.o
build/pf_restrict.o:    build/pf_utils.o build/pf_timer.o build/pf_hooks.o
build/pf_interpolate.o: build/pf_restrict.o build/pf_hooks.o
build/pf_parallel.o:    build/pf_interpolate.o build/pf_hooks.o
build/pf_fake.o:        build/pf_parallel.o build/pf_fakecomm.o
build/sdc_quadrature.o: build/pf_dtype.o build/sdc_poly.o
build/pf_quadrature.o:  build/sdc_quadrature.o
build/pf_pfasst.o:      build/pf_utils.o build/pf_quadrature.o \
                        build/pf_hooks.o build/pf_options.o
build/pf_pthreads.o:    build/pf_timer.o build/pf_pfasst.o
build/pf_fakecomm.o:    build/pf_timer.o build/pf_pfasst.o
build/pf_options.o:     build/pf_version.o

ifdef NOMPI
build/pfasst.o:         build/pf_parallel.o build/pf_fake.o build/pf_pfasst.o \
                        build/pf_implicit.o build/pf_explicit.o build/pf_imex.o \
                        build/pf_pthreads.o build/pf_cpthreads.o \
                        build/pf_version.o build/pf_options.o build/pf_logger.o \
                        build/pf_ndarray.o build/pf_numpy.o
else
build/pfasst.o:         build/pf_parallel.o build/pf_fake.o build/pf_pfasst.o \
                        build/pf_implicit.o build/pf_explicit.o build/pf_imex.o \
                        build/pf_mpi.o build/pf_pthreads.o build/pf_cpthreads.o \
                        build/pf_version.o build/pf_options.o build/pf_logger.o \
                        build/pf_ndarray.o build/pf_numpy.o
endif
