exact_ad_cos – LibPFASST
exact_ad_cos Interface
9 statements
Source File
public interface exact_ad_cos
Calls
Contents
Module Procedures
exact_ad_cos_1d exact_ad_cos_1ds exact_ad_cos_1dz exact_ad_cos_2d exact_ad_cos_2dz exact_ad_cos_3d exact_ad_cos_3dz
Module Procedures
public subroutine exact_ad_cos_1d(t, uex, nu, v, kfreq, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(inout) :: uex(:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v
real(kind=pfdp), intent(in) :: kfreq(1)
real(kind=pfdp), intent(in) :: Lx
public subroutine exact_ad_cos_1ds(t, uex, nu, v, kfreq, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(inout) :: uex(:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v
real(kind=pfdp), intent(in) :: kfreq
real(kind=pfdp), intent(in) :: Lx
public subroutine exact_ad_cos_1dz(t, uex, nu, v, kfreq, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
complex(kind=pfdp), intent(inout) :: uex(:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v
real(kind=pfdp), intent(in) :: kfreq(1)
real(kind=pfdp), intent(in) :: Lx
public subroutine exact_ad_cos_2d(t, uex, nu, v, kfreq, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(inout) :: uex(:,:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v(2)
real(kind=pfdp), intent(in) :: kfreq(2)
real(kind=pfdp), intent(in) :: Lx(2)
public subroutine exact_ad_cos_2dz(t, uex, nu, v, kfreq, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
complex(kind=pfdp), intent(inout) :: uex(:,:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v(2)
real(kind=pfdp), intent(in) :: kfreq(2)
real(kind=pfdp), intent(in) :: Lx(2)
public subroutine exact_ad_cos_3d(t, uex, nu, v, kfreq, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(inout) :: uex(:,:,:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v(3)
real(kind=pfdp), intent(in) :: kfreq(3)
real(kind=pfdp), intent(in) :: Lx(3)
public subroutine exact_ad_cos_3dz(t, uex, nu, v, kfreq, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
complex(kind=pfdp), intent(inout) :: uex(:,:,:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v(3)
real(kind=pfdp), intent(in) :: kfreq(3)
real(kind=pfdp), intent(in) :: Lx(3)
Call graph
exact_ad_cos calls exact_ad_cos_2d, exact_ad_cos_2dz, exact_ad_cos_1ds, exact_ad_cos_1d, exact_ad_cos_3d, exact_ad_cos_1dz, exact_ad_cos_3dz
exact_ad_cos_2d calls ad_cos_ex
exact_ad_cos_2dz calls ad_cos_ex
exact_ad_cos_1ds calls ad_cos_ex
exact_ad_cos_1d calls ad_cos_ex
exact_ad_cos_3d calls ad_cos_ex
exact_ad_cos_1dz calls ad_cos_ex
exact_ad_cos_3dz calls ad_cos_ex