exact_burg_sin – LibPFASST
exact_burg_sin Interface
8 statements
Source File
public interface exact_burg_sin
Calls
Contents
Module Procedures
exact_burg_sin_1d exact_burg_sin_1dz exact_burg_sin_2d exact_burg_sin_2dz exact_burg_sin_3d exact_burg_sin_3dz
Module Procedures
public subroutine exact_burg_sin_1d(t, uex, nu, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(inout) :: uex(:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: Lx
public subroutine exact_burg_sin_1dz(t, uex, nu, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
complex(kind=pfdp), intent(inout) :: uex(:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: Lx
public subroutine exact_burg_sin_2d(t, uex, nu, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(inout) :: uex(:,:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: Lx(2)
public subroutine exact_burg_sin_2dz(t, uex, nu, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
complex(kind=pfdp), intent(inout) :: uex(:,:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: Lx(2)
public subroutine exact_burg_sin_3d(t, uex, nu, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(inout) :: uex(:,:,:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: Lx(3)
public subroutine exact_burg_sin_3dz(t, uex, nu, Lx)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
complex(kind=pfdp), intent(inout) :: uex(:,:,:)
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: Lx(3)
Call graph
exact_burg_sin calls exact_burg_sin_3d, exact_burg_sin_3dz, exact_burg_sin_2d, exact_burg_sin_2dz, exact_burg_sin_1dz, exact_burg_sin_1d
exact_burg_sin_3d calls burg_sin_ex
exact_burg_sin_3dz calls burg_sin_ex
exact_burg_sin_2d calls burg_sin_ex
exact_burg_sin_2dz calls burg_sin_ex
exact_burg_sin_1dz calls burg_sin_ex
exact_burg_sin_1d calls burg_sin_ex