ad_cos_ex – LibPFASST
ad_cos_ex Function
12 statements
Source File
public function ad_cos_ex(t, x, nu, v, kfreq, Lx) result(u)
Routine to return the exact solution for advection diffusion Routine to return the exact solution for advection diffusion
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(in) :: x
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v
real(kind=pfdp), intent(in) :: kfreq
real(kind=pfdp), intent(in) :: Lx
Return Value real(kind=pfdp)
Called by
Contents
Source Code
ad_cos_ex
Source Code
  function ad_cos_ex(t, x,nu,v,kfreq,Lx) result(u)
    real(pfdp), intent(in)  :: t
    real(pfdp), intent(in)  :: x
    real(pfdp), intent(in)  :: v
    real(pfdp), intent(in)  :: nu
    real(pfdp), intent(in)  :: kfreq
    real(pfdp), intent(in)  :: Lx
    real(pfdp)  :: u
    real(pfdp) ::  omega
    omega = kfreq*two_pi/Lx
    u=cos(omega*(x-t*v))*exp(-omega*omega*nu*t)
  end function ad_cos_ex
Call graph
exact_ad_cos_3dz calls ad_cos_ex
exact_ad_cos_2d calls ad_cos_ex
exact_ad_cos_2dz calls ad_cos_ex
exact_ad_cos_3d calls ad_cos_ex
exact_ad_cos_1dz calls ad_cos_ex
exact_ad_cos_1d calls ad_cos_ex
exact_ad_cos calls exact_ad_cos_3dz, exact_ad_cos_2d, exact_ad_cos_2dz, exact_ad_cos_3d, exact_ad_cos_1dz, exact_ad_cos_1d