ad_exp_ex – LibPFASST
ad_exp_ex Function
25 statements
Source File
public function ad_exp_ex(t, x, nu, v, Lx) result(u)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(in) :: x
real(kind=pfdp), intent(in) :: nu
real(kind=pfdp), intent(in) :: v
real(kind=pfdp), intent(in) :: Lx
Return Value real(kind=pfdp)
Called by
Contents
Source Code
ad_exp_ex
Source Code
  function ad_exp_ex(t, x,nu,v,Lx) result(u)
    real(pfdp), intent(in)  :: t
    real(pfdp), intent(in)  :: x
    real(pfdp), intent(in)  :: v
    real(pfdp), intent(in)  :: nu
    real(pfdp), intent(in)  :: Lx
    real(pfdp)  :: u
    integer    :: nx, i, ii, k,nbox
    real(pfdp) ::  xx,c,t0
    u=0.0_pfdp
    if (nu .gt. 0.0) then
       t0=0.0025_pfdp/nu
       nbox = ceiling(sqrt(4.0_pfdp*nu*(t0+t)*37.0_pfdp))  !  Decide how many periodic images
       do k = -nbox,nbox
          xx = x- 0.5_pfdp*Lx - t*v + REAL(k,pfdp)*Lx
          u = u + sqrt(t0)/sqrt(t0+t)*exp(-xx*xx/(4.0_pfdp*nu*(t0+t)))
       end do
    else
       nbox = ceiling(sqrt(37.0d0))  !  Decide how many periodic images
       do k = -nbox,nbox
          xx = x - 0.5_pfdp*Lx- t*v  + REAL(k,pfdp)*Lx
          u = u + exp(-xx*xx/(4.0_pfdp*0.0025_pfdp))
       end do
    end if
  end function ad_exp_ex
Call graph
exact_ad_exp_3d calls ad_exp_ex
exact_ad_exp_1dz calls ad_exp_ex
exact_ad_exp_3dz calls ad_exp_ex
exact_ad_exp_1d calls ad_exp_ex
exact_ad_exp_2d calls ad_exp_ex
exact_ad_exp_2dz calls ad_exp_ex
exact_ad_exp calls exact_ad_exp_3d, exact_ad_exp_1dz, exact_ad_exp_3dz, exact_ad_exp_1d, exact_ad_exp_2d, exact_ad_exp_2dz