amisdcQ_sweep – LibPFASST
amisdcQ_sweep Subroutine
8 statements
Source File
public subroutine amisdcQ_sweep(this, pf, lev, t0, dt)
Uses
pf_mod_timer
Arguments
Type Intent Optional Attributes Name
class(pf_amisdcQ_t), intent(inout) :: this
type(pf_pfasst_t), intent(inout) :: pf
class(pf_level_t), intent(inout) :: lev
real(kind=pfdp), intent(in) :: t0
real(kind=pfdp), intent(in) :: dt
Calls
Contents
Source Code
amisdcQ_sweep
Source Code
  subroutine amisdcQ_sweep(this, pf, lev, t0, dt)
    use pf_mod_timer
    class(pf_amisdcQ_t), intent(inout) :: this
    type(pf_pfasst_t),   intent(inout) :: pf
    real(pfdp),          intent(in)    :: dt, t0
    class(pf_level_t),   intent(inout) :: lev
    call sweep_coupled_implicit_terms(this, pf, lev, t0, dt)
  end subroutine amisdcQ_sweep
Call graph
amisdcq_sweep calls sweep_coupled_implicit_terms
sweep_coupled_implicit_terms calls start_timer, end_timer
start_timer calls mpi_wtime
end_timer calls mpi_wtime