AMReX_mfab_build – LibPFASST
AMReX_mfab_build Subroutine
28 statements
Source File
public subroutine AMReX_mfab_build(this, shape_in)
Uses
pf_mod_comm_mpi
Subroutine to allocate the array and set the size parameters
Arguments
Type Intent Optional Attributes Name
class(pf_encap_t), intent(inout) :: this
integer, intent(in) :: shape_in(:)
Calls
Called by
Contents
Source Code
AMReX_mfab_build
Source Code
  subroutine AMReX_mfab_build(this, shape_in)
    use pf_mod_comm_mpi
    class(pf_encap_t), intent(inout) :: this
    integer,           intent(in   ) :: shape_in(:)
    integer nn,psize,rank,ierr,k
    type(amrex_boxarray)  :: ba
    type(amrex_distromap) :: dm
    select type (this)
    class is (pf_AMReX_mfab_t)
       ! Define a single box covering the domain
       this%domain = amrex_box((/0,0,0/), (/shape_in(2),shape_in(3),shape_in(4)/))
       ! Initialize the boxarray "ba" from the single box "bx"
       call amrex_boxarray_build(ba, this%domain)
       this%max_grid_size=64
       ! Break up boxarray "ba" into chunks no larger than "max_grid_size" along a direction
       call ba%maxSize(this%max_grid_size)
       ! Build a DistributionMapping for the boxarray
       call amrex_distromap_build(dm, ba)
       ! This defines a amrex_geometry object.
       call amrex_geometry_build(this%geom, this%domain)
       ! Build data multifabs
       this%ncomp=shape_in(1)
       call amrex_multifab_build(this%mfab, ba, dm, this%ncomp, this%nghost)
       call amrex_distromap_destroy(dm)
       call amrex_boxarray_destroy(ba)
       if (ierr /=0) call pf_stop(__FILE__,__LINE__,'allocate fail, error=',ierr)
       this%ndim   = SIZE(shape_in)
       this%arr_shape = shape_in
       !  Make a shape the size of the grid with ghost cells
       this%pack_size(1:size(shape_in)) = shape_in
       do k=2,4
          if (this%pack_size(k)>1) this%pack_size(k)=this%pack_size(k)+2*this%nghost
       end do
    end select
  end subroutine AMReX_mfab_build
Call graph
amrex_mfab_build calls amrex_distromap_build, amrex_boxarray_destroy, amrex_boxarray_build, amrex_geometry_build, amrex_distromap_destroy, amrex_multifab_build, amrex_box
amrex_mfab_create_single calls amrex_mfab_build