AMReX_mfab_destroy – LibPFASST
AMReX_mfab_destroy Subroutine
9 statements
Source File
public subroutine AMReX_mfab_destroy(encap)
Subroutine to destroy array
Arguments
Type Intent Optional Attributes Name
class(pf_encap_t), intent(inout) :: encap
Calls
Contents
Source Code
AMReX_mfab_destroy
Source Code
  subroutine AMReX_mfab_destroy(encap)
    class(pf_encap_t), intent(inout) :: encap
    type(pf_AMReX_mfab_t), pointer :: pf_AMReX_mfab_obj
    integer ::  ierr
    pf_AMReX_mfab_obj => cast_as_AMReX_mfab(encap)
!    print *,'destroying AMReX_mfab'
    nullify(pf_AMReX_mfab_obj)
    call amrex_multifab_destroy(pf_AMReX_mfab_obj%mfab)
    call amrex_geometry_destroy(pf_AMReX_mfab_obj%geom)
  end subroutine AMReX_mfab_destroy
Call graph
amrex_mfab_destroy calls amrex_geometry_destroy, cast_as_amrex_mfab, amrex_multifab_destroy