AMReX_mfab_create_single – LibPFASST
AMReX_mfab_create_single Subroutine
10 statements
Source File
public subroutine AMReX_mfab_create_single(this, x, level_index, lev_shape)
Subroutine to create a single array
Arguments
Type Intent Optional Attributes Name
class(pf_AMReX_mfab_factory_t), intent(inout) :: this
class(pf_encap_t), intent(inout), allocatable :: x
integer, intent(in) :: level_index
integer, intent(in) :: lev_shape(:)
Calls
Contents
Source Code
AMReX_mfab_create_single
Source Code
  subroutine AMReX_mfab_create_single(this, x, level_index, lev_shape)
    class(pf_AMReX_mfab_factory_t), intent(inout)              :: this
    class(pf_encap_t),      intent(inout), allocatable :: x
    integer,                intent(in   )              :: level_index
    integer,                intent(in   )              :: lev_shape(:)
    integer :: ierr
    allocate(pf_AMReX_mfab_t::x,stat=ierr)
    if (ierr /=0) call pf_stop(__FILE__,__LINE__,'allocate fail, error=',ierr)
    call AMReX_mfab_build(x, lev_shape)
  end subroutine AMReX_mfab_create_single
Call graph
amrex_mfab_create_single calls amrex_mfab_build
amrex_mfab_build calls amrex_distromap_build, amrex_boxarray_destroy, amrex_boxarray_build, amrex_geometry_build, amrex_distromap_destroy, amrex_multifab_build, amrex_box