call_hooks – LibPFASST
call_hooks Subroutine
24 statements
Source File
public subroutine call_hooks(pf, level_index, hook)
Uses
pf_mod_timer
Subroutine to call hooks associated with the hook and level
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
main pfasst structure
integer, intent(in) :: level_index
which pfasst level to call hook
integer, intent(in) :: hook
which hook to call
Called by
Contents
Source Code
call_hooks
Source Code
  subroutine call_hooks(pf, level_index, hook)
    use pf_mod_timer
    type(pf_pfasst_t), intent(inout), target :: pf         !! main pfasst structure
    integer,           intent(in)            :: level_index  !! which pfasst level to call hook
    integer,           intent(in)            :: hook       !! which hook to call
    integer :: i  !!  hook loop index
    integer :: l  !!  level loop index
    pf%state%hook = hook
    if (level_index == -1) then  ! Do to all levels
       do l = 1, pf%nlevels
          if (pf%save_timings > 1) call pf_start_timer(pf, T_HOOKS,l)
          do i = 1, pf%nhooks(l,hook)
             call pf%hooks(l,hook,i)%proc(pf,l)
          end do
          if (pf%save_timings > 1) call pf_stop_timer(pf, T_HOOKS,l)
       end do
    else  ! Do to just level level_index
       if (pf%save_timings > 1) call pf_start_timer(pf, T_HOOKS,level_index)
       do i = 1, pf%nhooks(level_index,hook)
          call pf%hooks(level_index,hook,i)%proc(pf,level_index)
       end do
       if (pf%save_timings > 1) call pf_stop_timer(pf, T_HOOKS,level_index)
    end if
  end subroutine call_hooks
Call graph
pf_check_convergence_block calls call_hooks
exp_sweep calls call_hooks
imk_actually_sweep calls call_hooks
pf_parareal_block_run calls call_hooks, pf_check_convergence_block, pf_parareal_predictor
verlet_sweep calls call_hooks
restrict_time_space_fas calls call_hooks
pf_predictor_oc calls call_hooks, restrict_time_space_fas, interpolate_time_space
interpolate_q0 calls call_hooks
interpolate_qend calls call_hooks
misdcq_sweep calls call_hooks
misdcq_oc_sweep calls call_hooks
pf_check_convergence_oc calls call_hooks
imexq_oc_sweep calls call_hooks
imex_sweep calls call_hooks
mkrk_step calls call_hooks
pf_predictor calls call_hooks, restrict_time_space_fas, interpolate_time_space
rk_step calls call_hooks
interpolate_time_space calls call_hooks
pf_block_run calls call_hooks, pf_check_convergence_block, pf_predictor, pf_vcycle_pysdc, pf_vcycle
magpicard_sweep calls call_hooks
pf_parareal_predictor calls call_hooks
pf_pfasst_block_oc calls call_hooks, pf_predictor_oc, pf_check_convergence_oc, pf_v_cycle_oc
pf_v_cycle_oc calls restrict_time_space_fas, interpolate_time_space
pf_vcycle_pysdc calls restrict_time_space_fas, interpolate_q0, interpolate_time_space
imk_sweep calls imk_actually_sweep, mkrk_step, rk_step
pf_parareal_run calls pf_parareal_block_run
pf_pfasst_run calls pf_block_run
pf_vcycle calls restrict_time_space_fas, interpolate_q0, interpolate_time_space