conv_3d – LibPFASST
conv_3d Subroutine
7 statements
Source File
public subroutine conv_3d(this, g)
Arguments
Type Intent Optional Attributes Name
class(pf_fft_t), intent(inout) :: this
complex(kind=pfdp), intent(in) :: g(:,:,:)
Calls
Contents
Source Code
conv_3d
Source Code
    subroutine conv_3d(this, g)
        ! Variable Types
        class(pf_fft_t), intent(inout) :: this
        complex(pfdp), intent(in) :: g(:,:,:)
        ! Compute Convolution
        call fftf(this)
        this%wk_3d = this%wk_3d * g
        call fftb(this)
    end subroutine conv_3d
Call graph
conv_3d calls fftf, fftb
fftf calls pf_stop, fftw_execute_dft
fftb calls pf_stop, fftw_execute_dft