dump_timingsl – LibPFASST
dump_timingsl Subroutine
36 statements
Source File
public subroutine dump_timingsl(this, pf)
Arguments
Type Intent Optional Attributes Name
type(pf_results_t), intent(inout) :: this
type(pf_pfasst_t), intent(inout) :: pf
Calls
Contents
Source Code
dump_timingsl
Source Code
  subroutine dump_timingsl(this,pf)
    type(pf_results_t), intent(inout) :: this
    type(pf_pfasst_t), intent(inout) :: pf
    character(len = 128   ) :: pname     !!  processor name
    character(len = 256   ) :: fullname  !!  output file name for runtimes
    character(len = 128   ) :: datpath  !!  directory path
    character(len = 128   ) :: strng      !  used for string conversion
    integer :: j, iout,system,nlev,k,kmax
    real(pfdp) :: qarr(pf%nlevels)
    !  Write a json file with timer numbers and times
    fullname = trim(this%datpath) // '/runtime.json'
    iout = 4000+pf%rank !  Use processor dependent file number
    nlev=pf%nlevels
    !  output timings
    open(iout, file=trim(fullname), form='formatted',err=998)
    write(iout,*) '{'
    kmax=1
    if (pf%save_timings > 1) kmax=4
    do k=1,kmax
       write(iout,"(A24,A1,e14.6,A1)") wrap_timer_name(timer_names(k)), ': ', pf%pf_timers%runtimes(k,1), ','
    end do
    if (pf%save_timings > 1) then
       do k=kmax+1,PF_NUM_TIMERS
          if (nlev .eq. 1) then
             write(iout,"(A24,A1,e14.6,A1)") wrap_timer_name(timer_names(k)), ':', pf%pf_timers%runtimes(k,1), ','
          else
             qarr=pf%pf_timers%runtimes(k,1:nlev)
             strng=trim(convert_real_array(qarr,nlev))
             write(iout,"(A24,A1,A60,A1)")  wrap_timer_name(timer_names(k)),':', adjustl(strng), ','
          end if
       end do
    end if
    write(iout,*) '"foo":"0"'
    write(iout,*) '}'
    close(iout)
    return
998 call pf_stop(__FILE__,__LINE__, "Error opening json file")
  end subroutine dump_timingsl
Call graph
dump_timingsl calls wrap_timer_name, timer_names, convert_real_array