end_timer – LibPFASST
end_timer Subroutine
10 statements
Source File
public subroutine end_timer(pf, timer)
Subroutine to stop a timer
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout) :: pf
integer, intent(in) :: timer
Calls
Called by
Contents
Source Code
end_timer
Source Code
  subroutine end_timer(pf, timer)
    type(pf_pfasst_t), intent(inout) :: pf
    integer,           intent(in)    :: timer
    double precision :: t
    t=MPI_Wtime()
    pf%runtimes(timer) = pf%runtimes(timer) + t - pf%timers(timer)
    if (pf%echo_timings) then
       write(*, '("timer:",a16,", rank: ",i3,", step: ",i4, ", level: ", i3,' &
            // '", iter: ",i3, f23.8,f23.8,f23.8)') &
            timer_names(timer), pf%rank, &
            pf%state%step, pf%state%level_index, pf%state%iter,  &
            t-pf%timers(timer), pf%runtimes(timer), t-pf%timers(TTOTAL)
    end if
  end subroutine end_timer
Call graph
end_timer calls mpi_wtime
sweep_coupled_implicit_terms calls end_timer
imk_actually_sweep calls end_timer, pf_residual, call_hooks
misdcq_sweep calls end_timer, pf_residual, call_hooks
pf_block_run calls end_timer, pf_predictor, call_hooks, pf_v_cycle, pf_check_convergence_block
pf_parareal_predictor calls end_timer, call_hooks
interpolate_time_space calls end_timer, call_hooks
pf_predictor calls end_timer, interpolate_time_space, pf_residual, restrict_time_space_fas, call_hooks
pf_parareal_block_run calls end_timer, pf_parareal_predictor, call_hooks, pf_check_convergence_block
magpicard_sweep calls end_timer, pf_residual, call_hooks
imex_sweep calls end_timer, pf_residual, call_hooks
interpolate_qend calls end_timer, call_hooks
imexq_oc_sweep calls end_timer, pf_residual, call_hooks
pf_residual calls end_timer
misdc_sweep calls end_timer
verlet_sweep calls end_timer, pf_residual, call_hooks
pf_predictor_oc calls end_timer, interpolate_time_space, pf_residual, restrict_time_space_fas, call_hooks
amisdc_sweep calls end_timer
restrict_time_space_fas calls end_timer, call_hooks
call_hooks calls end_timer
pf_pfasst_block_oc calls end_timer, pf_predictor_oc, call_hooks, pf_check_convergence_oc, pf_v_cycle_oc
interpolate_q0 calls end_timer, call_hooks
pf_pfasst_run calls pf_block_run
pf_v_cycle calls interpolate_time_space, pf_residual, restrict_time_space_fas, interpolate_q0
pf_check_convergence_block calls call_hooks
rk_step calls pf_residual, call_hooks
exp_sweep calls pf_residual, call_hooks
pf_parareal_run calls pf_parareal_block_run
mkrk_step calls pf_residual, call_hooks
misdcq_oc_sweep calls pf_residual, call_hooks
pf_check_convergence_oc calls call_hooks
imk_sweep calls imk_actually_sweep, rk_step, mkrk_step
pf_v_cycle_oc calls interpolate_time_space, pf_residual, restrict_time_space_fas
amisdcq_sweep calls sweep_coupled_implicit_terms