exp_sweep – LibPFASST
exp_sweep Subroutine
59 statements
Source File
public subroutine exp_sweep(this, pf, level_index, t0, dt, nsweeps, flags)
Uses
pf_mod_timer
pf_mod_hooks
Arguments
Type Intent Optional Attributes Name
class(pf_exp_t), intent(inout) :: this
type(pf_pfasst_t), intent(inout), target :: pf
PFASST structure
integer, intent(in) :: level_index
which level to sweep on
real(kind=pfdp), intent(in) :: t0
Time at beginning of time step
real(kind=pfdp), intent(in) :: dt
time step size
integer, intent(in) :: nsweeps
number of sweeps to do
integer, intent(in), optional :: flags
Calls
Contents
Source Code
exp_sweep
Source Code
    subroutine exp_sweep(this, pf, level_index, t0, dt,nsweeps, flags)
        use pf_mod_timer
        use pf_mod_hooks
        ! arguments
        class(pf_exp_t),   intent(inout) :: this
        type(pf_pfasst_t), intent(inout), target :: pf   !!  PFASST structure
        integer,           intent(in)    :: level_index  !!  which level to sweep on
        real(pfdp),        intent(in)    :: t0           !!  Time at beginning of time step
        real(pfdp),        intent(in)    :: dt           !!  time step size
        integer,           intent(in)    :: nsweeps      !!  number of sweeps to do
        integer, optional, intent(in)    :: flags
        ! local variables
        type(pf_level_t), pointer :: lev
        integer                    :: m, nnodes, j, k
        real(pfdp)                 :: t
        lev => pf%levels(level_index)
        nnodes = lev%nnodes
        ! error sweeps
        do k = 1, nsweeps
           call call_hooks(pf, level_index, PF_PRE_SWEEP)
           if (pf%save_timings > 1) call pf_start_timer(pf, T_SWEEP,level_index)
           pf%state%sweep=k
           ! NOTE: ensure that lev%F has been properly initialized here
           do j = 1, nnodes
              call this%f_old(j)%copy(lev%F(j,1))  ! Save old f
           end do
           if (k .eq. 1) then
              call lev%Q(1)%copy(lev%q0)
              if (pf%save_timings > 1) call pf_start_timer(pf, T_FEVAL,level_index)
              call this%f_eval(lev%Q(1), t0, level_index, lev%F(1,1))      ! compute F_j^{[k+1]}
              if (pf%save_timings > 1) call pf_stop_timer(pf, T_FEVAL,level_index)
           end if
           t = t0
           do j = 1, nnodes - 1
              t = t0 + dt * this%eta(j)
              ! form b vectors
              call LocalDerivsAtNode(this, j, nnodes, this%f_old, this%b)  ! phi expansion for exponential picard integral
              call this%b(1)%copy(lev%Q(j))  ! add term \phi_0(tL) y_n
              call this%b(2)%axpy(REAL(-1.0, pfdp), this%f_old(j))         ! add -\phi_1(tL) F_j^{[k]}
              if (pf%save_timings > 1) call pf_start_timer(pf, T_FEVAL,level_index)
              call this%f_eval(lev%Q(j), t, level_index, lev%F(j,1))      ! compute F_j^{[k+1]}
              if (pf%save_timings > 1) call pf_stop_timer(pf, T_FEVAL,level_index)
              call this%b(2)%axpy(REAL(1.0, pfdp), lev%F(j,1))          ! add \phi_1(tL) F_j^{[k+1]}
              ! compute phi products
              if (this%use_phib) then
                 call this%phib(this%eta(j), dt, this%b, lev%Q(j+1))
              else
                 call this%swpPhib(j, dt, this%b, lev%Q(j+1))
              end if
              !  Now we have to add in the tauQ
              if (level_index < pf%state%finest_level) then
                 call lev%Q(j+1)%axpy(1.0_pfdp, lev%tauQ(j))
                 if (j > 1) then     ! The tau is not node to node, so subtract out
                    call lev%Q(j+1)%axpy(-1.0_pfdp, lev%tauQ(j-1))
                 end if
              end if
           end do  !  Substepping over nodes
           if (pf%save_timings > 1) call pf_start_timer(pf, T_FEVAL,level_index)
           call this%f_eval(lev%Q(nnodes), t0 + dt, level_index, lev%F(nnodes,1))   ! eval last nonlinear term
           if (pf%save_timings > 1) call pf_stop_timer(pf, T_FEVAL,level_index)
           call pf_residual(pf, level_index, dt)
           call lev%qend%copy(lev%Q(lev%nnodes))
           if (pf%save_timings > 1) call pf_stop_timer(pf, T_SWEEP,level_index)
           call call_hooks(pf, level_index, PF_POST_SWEEP)
        end do  !  Sweeps
    end subroutine exp_sweep
Call graph
exp_sweep calls localderivsatnode, call_hooks, pf_residual
pf_residual calls pf_set_resid