FN_VGetFVec – LibPFASST
FN_VGetFVec Function
7 statements
Source File
public function FN_VGetFVec(sunvec_x) result(x)
Arguments
Type Intent Optional Attributes Name
type(N_Vector) :: sunvec_x
Return Value type(FVec), pointer
Called by
Contents
Source Code
FN_VGetFVec
Source Code
  function FN_VGetFVec(sunvec_x) result(x)
    implicit none
    type(N_Vector)         :: sunvec_x
    type(FVec),    pointer :: x
    ! extract Fortran matrix structure to output
    call c_f_pointer(sunvec_x%content, x)
    return
  end function FN_VGetFVec
Call graph
fn_vprod_fortran calls fn_vgetfvec
fn_vdotprod_fortran calls fn_vgetfvec
fn_vconst_fortran calls fn_vgetfvec
fn_vspace_fortran calls fn_vgetfvec
fn_vl1norm_fortran calls fn_vgetfvec
fn_vwl2norm_fortran calls fn_vgetfvec, fn_vwsqrsum_fortran
fn_vminquotient_fortran calls fn_vgetfvec
fn_vscale_fortran calls fn_vgetfvec
fn_vmin_fortran calls fn_vgetfvec
fn_vcompare_fortran calls fn_vgetfvec
fn_vinv_fortran calls fn_vgetfvec
fn_vwrmsnorm_fortran calls fn_vgetfvec, fn_vwsqrsum_fortran
fn_vabs_fortran calls fn_vgetfvec
fn_vgetlength_fortran calls fn_vgetfvec
fn_vmaxnorm_fortran calls fn_vgetfvec
fn_vinvtest_fortran calls fn_vgetfvec
fn_vwsqrsummask_fortran calls fn_vgetfvec
fn_vwrmsnormmask_fortran calls fn_vgetfvec, fn_vwsqrsummask_fortran
fn_vlinearsum_fortran calls fn_vgetfvec
fn_vdiv_fortran calls fn_vgetfvec
fn_vdestroy_fortran calls fn_vgetfvec
fn_vclone_fortran calls fn_vgetfvec
fn_vaddconst_fortran calls fn_vgetfvec
fn_vwsqrsum_fortran calls fn_vgetfvec
fn_vconstrmask_fortran calls fn_vgetfvec