imex_sweep – LibPFASST
imex_sweep Subroutine
72 statements
Source File
public subroutine imex_sweep(this, pf, level_index, t0, dt, nsweeps, flags)
Uses
pf_mod_timer
pf_mod_hooks
Perform nsweeps SDC sweeps on level level_index and set qend appropriately. Loop over sweeps
Loop over substeps Loop over substeps Accumulate rhs
Add the starting value
Solve for the implicit piece Compute explicit function on new value End substep loop
Arguments
Type Intent Optional Attributes Name
class(pf_imexR_sweeper_t), intent(inout) :: this
Inputs
type(pf_pfasst_t), intent(inout), target :: pf
PFASST structure
integer, intent(in) :: level_index
level on which to sweep
real(kind=pfdp), intent(in) :: t0
time at beginning of time step
real(kind=pfdp), intent(in) :: dt
time step size
integer, intent(in) :: nsweeps
number of sweeps to do
integer, intent(in), optional :: flags
sweep specific flags
Calls
Contents
Source Code
imex_sweep
Source Code
  subroutine imex_sweep(this, pf, level_index, t0, dt,nsweeps, flags)
    use pf_mod_timer
    use pf_mod_hooks
    !>  Inputs
    class(pf_imexR_sweeper_t), intent(inout) :: this
    type(pf_pfasst_t), intent(inout),target :: pf    !!  PFASST structure
    integer,           intent(in)    :: level_index  !!  level on which to sweep
    real(pfdp),        intent(in   ) :: t0           !!  time at beginning of time step
    real(pfdp),        intent(in   ) :: dt           !!  time step size
    integer,           intent(in)    :: nsweeps      !!  number of sweeps to do
    integer, optional, intent(in   ) :: flags        !!  sweep specific flags
    !>  Local variables
    type(pf_level_t), pointer :: lev    !!  points to current level
    integer     :: m, n,k,m0   !!  Loop variables
    real(pfdp)  :: t        !!  Time at nodes
    lev => pf%levels(level_index)   !  Assign level pointer
    call pf_residual(pf, level_index, dt)
    do k = 1,nsweeps   !!  Loop over sweeps
       call call_hooks(pf, level_index, PF_PRE_SWEEP)
       if (pf%save_timings > 1) call pf_start_timer(pf, T_SWEEP,level_index)
       pf%state%sweep=k
       !  Store the current F values
       if (k .eq. 1) then
          m0=1
       else
          m0=2
       end if
       do m = m0, lev%nnodes  !!  Loop over substeps
          if (this%explicit) &
               call this%F_oldE(m)%copy(lev%F(m,1))
          if (this%implicit) &
               call this%F_oldI(m)%copy(lev%F(m,2))
       end do
       !  Recompute the first function value if this is first sweep
       if (k .eq. 1) then
          call lev%Q(1)%copy(lev%q0)
          if (this%explicit) then
             if (pf%save_timings > 1) call pf_start_timer(pf,T_FEVAL,level_index)
             call this%f_eval(lev%Q(1), t0, level_index, lev%F(1,1),1)
             if (pf%save_timings > 1) call pf_stop_timer(pf,T_FEVAL,level_index)
          end if
          if (this%implicit) then
             if (pf%save_timings > 1) call pf_start_timer(pf,T_FEVAL,level_index)
             call this%f_eval(lev%Q(1), t0, level_index, lev%F(1,2),2)
             if (pf%save_timings > 1) call pf_stop_timer(pf,T_FEVAL,level_index)
          end if
       end if
       t = t0
       ! do the sub-stepping in sweep
       do m = 1, lev%nnodes-1  !!  Loop over substeps
          t = t + dt*this%dtsdc(m)
          !>  Accumulate rhs
          call this%rhs%copy(lev%R(m))
          call this%F_oldE(m)%axpy(-1.0_pfdp, lev%F(m,1))
          call this%F_oldI(m)%axpy(-1.0_pfdp, lev%F(m,2))
          do n = 1, m
             if (this%explicit) &
                  call this%rhs%axpy(-dt*this%QtilE(m,n), this%F_oldE(n))
             if (this%implicit) &
                  call this%rhs%axpy(-dt*this%QtilI(m,n), this%F_oldI(n))
          end do
          !>  Add the starting value
          call this%rhs%axpy(1.0_pfdp, lev%Q(m+1))
          !>  Solve for the implicit piece
          if (this%implicit) then
             call this%rhs%axpy(-dt*this%QtilI(m,m+1), this%F_oldI(m+1))
             if (pf%save_timings > 1) call pf_start_timer(pf,T_FCOMP,level_index)
             call this%f_comp(lev%Q(m+1), t, dt*this%QtilI(m,m+1), this%rhs, level_index,lev%F(m+1,2),2)
             if (pf%save_timings > 1) call pf_stop_timer(pf,T_FCOMP,level_index)
          else
             call lev%Q(m+1)%copy(this%rhs)
          end if
          !>  Compute explicit function on new value
          if (this%explicit) then
             if (pf%save_timings > 1) call pf_start_timer(pf,T_FEVAL,level_index)
             call this%f_eval(lev%Q(m+1), t, level_index, lev%F(m+1,1),1)
             if (pf%save_timings > 1) call pf_stop_timer(pf,T_FEVAL,level_index)
          end if
       end do  !!  End substep loop
       call pf_residual(pf, level_index, dt)
       call lev%qend%copy(lev%Q(lev%nnodes))
       if (pf%save_timings > 1) call pf_stop_timer(pf, T_SWEEP,level_index)
       call call_hooks(pf, level_index, PF_POST_SWEEP)
    end do  !  End loop on sweeps
  end subroutine imex_sweep
Call graph
imex_sweep calls pf_residual, call_hooks
pf_residual calls pf_set_resid