imex_sweep – LibPFASST
imex_sweep Subroutine
85 statements
Source File
public subroutine imex_sweep(this, pf, level_index, t0, dt, nsweeps, flags)
Uses
pf_mod_hooks
Perform nsweeps SDC sweeps on level level_index and set qend appropriately. Loop over sweeps Loop over substeps Accumulate rhs Add the integral term
Add the starting value Solve for the implicit piece Compute explicit function on new value End substep loop
Arguments
Type Intent Optional Attributes Name
class(pf_imex_sweeper_t), intent(inout) :: this
Inputs
type(pf_pfasst_t), intent(inout), target :: pf
PFASST structure
integer, intent(in) :: level_index
level on which to sweep
real(kind=pfdp), intent(in) :: t0
time at beginning of time step
real(kind=pfdp), intent(in) :: dt
time step size
integer, intent(in) :: nsweeps
number of sweeps to do
integer, intent(in), optional :: flags
sweep specific flags
Calls
Contents
Source Code
imex_sweep
Source Code
  subroutine imex_sweep(this, pf, level_index, t0, dt,nsweeps, flags)
    use pf_mod_hooks
    !>  Inputs
    class(pf_imex_sweeper_t), intent(inout) :: this
    type(pf_pfasst_t), intent(inout),target :: pf    !!  PFASST structure
    integer,           intent(in)    :: level_index  !!  level on which to sweep
    real(pfdp),        intent(in   ) :: t0           !!  time at beginning of time step
    real(pfdp),        intent(in   ) :: dt           !!  time step size
    integer,           intent(in)    :: nsweeps      !!  number of sweeps to do
    integer, optional, intent(in   ) :: flags        !!  sweep specific flags
    !>  Local variables
    type(pf_level_t), pointer :: lev    !!  points to current level
    integer     :: m,n,k   !!  Loop variables
    real(pfdp)  :: t        !!  Time at nodes
    lev => pf%levels(level_index)   !  Assign level pointer
    sweeps: do k = 1,nsweeps   !!  Loop over sweeps
       pf%state%sweep=k
       call call_hooks(pf, level_index, PF_PRE_SWEEP)
       call pf_start_timer(pf, T_SWEEP,level_index)
       !  Add terms from previous iteration  (not passing CI tests)
       !do m = 1, lev%nnodes-1
       !   call lev%I(m)%setval(0.0_pfdp)
       !end do
        !if (this%explicit) call pf_apply_mat(lev%I, dt, this%QdiffE, lev%F(:,1), .false.)
       !if (this%implicit) call pf_apply_mat(lev%I, dt, this%QdiffI, lev%F(:,2), .false.)
       ! compute integrals and add fas correction
       do m = 1, lev%nnodes-1
          call lev%I(m)%setval(0.0_pfdp)
          if (this%explicit) then
             do n = 1, lev%nnodes
                call lev%I(m)%axpy(dt*this%QdiffE(m,n), lev%F(n,1))
             end do
          end if
          if (this%implicit) then
             do n = 1, lev%nnodes
                call lev%I(m)%axpy(dt*this%QdiffI(m,n), lev%F(n,2))
             end do
          end if
       end do
       !  Add the tau FAS correction
       if (level_index < pf%state%finest_level) then
          do m = 1, lev%nnodes-1
             call lev%I(m)%axpy(1.0_pfdp, lev%tauQ(m))
             if (m>1 .and. pf%use_Sform) then
                call lev%I(m)%axpy(-1.0_pfdp, lev%tauQ(m-1))
             end if
          end do
       end if
       !  Recompute the first function value if this is first sweep
       if (k .eq. 1) then
          call lev%Q(1)%copy(lev%q0)
          if (this%explicit) then
             if (pf%save_timings > 1) call pf_start_timer(pf,T_FEVAL,level_index)
             call this%f_eval(lev%Q(1), t0, level_index, lev%F(1,1),1)
             if (pf%save_timings > 1) call pf_stop_timer(pf,T_FEVAL,level_index)
          end if
          if (this%implicit) then
             if (pf%save_timings > 1) call pf_start_timer(pf,T_FEVAL,level_index)
              call this%f_eval(lev%Q(1), t0, level_index, lev%F(1,2),2)
             if (pf%save_timings > 1) call pf_stop_timer(pf,T_FEVAL,level_index)
          end if
       end if
       t = t0
       ! do the sub-stepping in sweep
       substeps: do m = 1, lev%nnodes-1  !!  Loop over substeps
          t = t + dt*this%dtsdc(m)
          this%m_sub=m
          !>  Accumulate rhs
          call this%rhs%setval(0.0_pfdp)
          do n = 1, m
             if (this%explicit) &
                  call this%rhs%axpy(dt*this%QtilE(m,n), lev%F(n,1))
             if (this%implicit) &
                  call this%rhs%axpy(dt*this%QtilI(m,n), lev%F(n,2))
          end do
          !>  Add the integral term
          call this%rhs%axpy(1.0_pfdp, lev%I(m))
          !>  Add the starting value
          if (pf%use_Sform) then
             call this%rhs%axpy(1.0_pfdp, lev%Q(m))
          else
             call this%rhs%axpy(1.0_pfdp, lev%Q(1))
          end if
          !>  Solve for the implicit piece
          if (this%implicit) then
             if (pf%save_timings > 1) call pf_start_timer(pf,T_FCOMP,level_index)
             call this%f_comp(lev%Q(m+1), t, dt*this%QtilI(m,m+1), this%rhs, level_index,lev%F(m+1,2),2)
             if (pf%save_timings > 1) call pf_stop_timer(pf,T_FCOMP,level_index)
          else
             call lev%Q(m+1)%copy(this%rhs)
          end if
          !>  Compute explicit function on new value
          if (this%explicit) then
             if (pf%save_timings > 1) call pf_start_timer(pf,T_FEVAL,level_index)
             call this%f_eval(lev%Q(m+1), t, level_index, lev%F(m+1,1),1)
             if (pf%save_timings > 1) call pf_stop_timer(pf,T_FEVAL,level_index)
          end if
       end do substeps !!  End substep loop
       call pf_residual(pf, level_index, dt)
       call lev%qend%copy(lev%Q(lev%nnodes))
       call pf_stop_timer(pf, T_SWEEP,level_index)
       call call_hooks(pf, level_index, PF_POST_SWEEP)
    end do sweeps  !  End loop on sweeps
  end subroutine imex_sweep
Call graph
imex_sweep calls pf_stop_timer, call_hooks, pf_start_timer, pf_residual
pf_stop_timer calls mpi_wtime
pf_start_timer calls mpi_wtime
pf_residual calls pf_set_resid