kdv_ex – LibPFASST
kdv_ex Function
11 statements
Source File
public function kdv_ex(t, x, beta, Lx) result(u)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(in) :: x
real(kind=pfdp), intent(in) :: beta
real(kind=pfdp), intent(in) :: Lx
Return Value real(kind=pfdp)
Called by
Contents
Source Code
kdv_ex
Source Code
    function kdv_ex(t, x,beta,Lx) result(u)
    real(pfdp), intent(in)  :: t
    real(pfdp), intent(in)  :: x
    real(pfdp), intent(in)  :: beta
    real(pfdp), intent(in)  :: Lx
    real(pfdp)  :: u
    real(pfdp) :: a,s
    a=beta*(x-0.375_pfdp*Lx-t)
    s = 2.0_pfdp/(exp(a)+exp(-a))
    u=s*s
  end function kdv_ex
Call graph
exact_kdv_2dz calls kdv_ex
exact_kdv_1d calls kdv_ex
exact_kdv_3dz calls kdv_ex
exact_kdv_1dz calls kdv_ex
exact_kdv calls exact_kdv_1d, exact_kdv_1dz