misdcQ_oc_sweep – LibPFASST
misdcQ_oc_sweep Subroutine
135 statements
Source File
public subroutine misdcQ_oc_sweep(this, pf, level_index, t0, dt, nsweeps, flags)
Uses
pf_mod_timer
pf_mod_hooks
Arguments
Type Intent Optional Attributes Name
class(pf_misdcQ_oc_t), intent(inout) :: this
type(pf_pfasst_t), intent(inout), target :: pf
integer, intent(in) :: level_index
real(kind=pfdp), intent(in) :: t0
real(kind=pfdp), intent(in) :: dt
integer, intent(in) :: nsweeps
integer, intent(in), optional :: flags
Calls
Contents
Source Code
misdcQ_oc_sweep
Source Code
  subroutine misdcQ_oc_sweep(this, pf, level_index, t0, dt, nsweeps, flags)
    use pf_mod_timer
    use pf_mod_hooks
    class(pf_misdcQ_oc_t),      intent(inout) :: this
    type(pf_pfasst_t), target,  intent(inout) :: pf
    integer,                    intent(in   ) :: level_index, nsweeps
    real(pfdp),                 intent(in   ) :: dt, t0
    integer,          optional, intent(in   ) :: flags
    !>  Local variables
    class(pf_level_t), pointer :: lev
    integer     :: k, m, n, which, Nnodes
    real(pfdp)  :: t, tend
    logical     :: sweep_y, sweep_p
    integer     :: step
    lev => pf%levels(level_index)   !  Assign level pointer
    call start_timer(pf, TLEVEL+lev%index-1)
    step = pf%state%step+1
    which = 0
    if (present(flags)) which = flags
    if (which .eq. 1) then
        sweep_y = .true.
        sweep_p = .false.
    else if (which .eq. 2) then
        sweep_y = .false.
        sweep_p = .true.
    else
       sweep_y = .true.
       sweep_p = .true.
    end if
    Nnodes = lev%nnodes
    tend = t0+dt
    do k = 1,nsweeps
       pf%state%sweep=k
       call call_hooks(pf, level_index, PF_PRE_SWEEP)
       ! compute integrals and add fas correction
        if( sweep_y ) then
        !  Forward in y
          do m = 1, Nnodes-1
            call lev%I(m)%setval(0.0_pfdp,1)
            call this%I3(m)%setval(0.0_pfdp,1)
            do n = 1, Nnodes
               call lev%I(m)%axpy(dt*this%QdiffE(m,n), lev%F(n,1), 1)
               call lev%I(m)%axpy(dt*this%QdiffI(m,n), lev%F(n,2), 1)
               call lev%I(m)%axpy(dt*lev%sdcmats%qmat(m,n), lev%F(n,3), 1)
               call this%I3(m)%axpy(dt*this%QtilI(m,n), lev%F(n,3), 1)
            end do
            if (level_index < pf%state%finest_level) then
               call lev%I(m)%axpy(1.0_pfdp, lev%tauQ(m),1)
            end if
          end do
        end if
        if( sweep_p ) then
        !  Backward in p
          do m =  Nnodes-1,1,-1
            call lev%I(m)%setval(0.0_pfdp,2)
            call this%I3(m)%setval(0.0_pfdp,2)
            do n = Nnodes,1,-1
               call lev%I(m)%axpy(dt*this%QdiffE(Nnodes-m,Nnodes+1-n), lev%F(n,1), 2)
               call lev%I(m)%axpy(dt*this%QdiffI(Nnodes-m,Nnodes+1-n), lev%F(n,2), 2)
               call lev%I(m)%axpy(dt*lev%sdcmats%qmat(Nnodes-m,Nnodes+1-n), lev%F(n,3), 2)
               call this%I3(m)%axpy(dt*this%QtilI(Nnodes-m,Nnodes+1-n), lev%F(n,3), 2)
            end do
            if (level_index < pf%state%finest_level) then
               call lev%I(m)%axpy(1.0_pfdp, lev%tauQ(m), 2)
            end if
          end do
        end if
       ! do the time-stepping
       if (k .eq. 1) then
         if( sweep_y ) then
            call lev%Q(1)%copy(lev%q0, 1)
            call this%f_eval(lev%Q(1), t0, lev%index, lev%F(1,1), 1, 1, 1, step)
            call this%f_eval(lev%Q(1), t0, lev%index, lev%F(1,2), 2, 1, 1, step)
            call this%f_eval(lev%Q(1), t0, lev%index, lev%F(1,3), 3, 1, 1, step)
         end if
         if( sweep_p ) then
            call lev%Q(Nnodes)%copy(lev%qend, 2)
            call this%f_eval(lev%Q(Nnodes), tend, lev%index, lev%F(Nnodes,1), 1, 2, Nnodes, step)
            call this%f_eval(lev%Q(Nnodes), tend, lev%index, lev%F(Nnodes,2), 2, 2, Nnodes, step)
            call this%f_eval(lev%Q(Nnodes), tend, lev%index, lev%F(Nnodes,3), 3, 2, Nnodes, step)
         end if
       end if ! k .eq. 1
       if (sweep_y) then
         t = t0
         do m = 1, lev%nnodes-1
            t = t + dt*this%dtsdc(m)
            call this%rhs%setval(0.0_pfdp,1)
            do n = 1, m
               call this%rhs%axpy(dt*this%QtilE(m,n), lev%F(n,1), 1)
               call this%rhs%axpy(dt*this%QtilI(m,n), lev%F(n,2), 1)
            end do
            !  Add the tau term
            call this%rhs%axpy(1.0_pfdp, lev%I(m), 1)
            !  Add the starting value
            call this%rhs%axpy(1.0_pfdp, lev%Q(1), 1)
            call this%f_comp(lev%Q(m+1), t, dt*this%QtilI(m,m+1), this%rhs, lev%index, lev%F(m+1,2), 2, 1)
            !  Now we need to do the final subtraction for the f3 piece
            call this%rhs%copy(lev%Q(m+1), 1)
            do n = 1, m
               call this%rhs%axpy(dt*this%QtilI(m,n), lev%F(n,3), 1)
            end do
            call this%rhs%axpy(-1.0_pfdp, this%I3(m), 1)
            call this%f_comp(lev%Q(m+1), t, dt*this%QtilI(m,m+1), this%rhs, lev%index, lev%F(m+1,3), 3, 1)
            call this%f_eval(lev%Q(m+1), t, lev%index, lev%F(m+1,1), 1, 1, m+1, step)
            call this%f_eval(lev%Q(m+1), t, lev%index, lev%F(m+1,2), 2, 1, m+1, step)
         end do
         !call pf_residual(pf, level_index, dt, 1)
         call lev%qend%copy(lev%Q(lev%nnodes), 1)
       end if ! sweep_y
       if (sweep_p) then
         t = tend
         do m = Nnodes-1, 1, -1
            t = t - dt*this%dtsdc(m)
            call this%rhs%setval(0.0_pfdp,2)
            do n = Nnodes, m+1,-1
               call this%rhs%axpy(dt*this%QtilE(Nnodes-m,Nnodes-n+1), lev%F(n,1), 2)
               call this%rhs%axpy(dt*this%QtilI(Nnodes-m,Nnodes-n+1), lev%F(n,2), 2)
            end do
            !  Add the tau term
            call this%rhs%axpy(1.0_pfdp, lev%I(m), 2)
            !  Add the starting value
            call this%rhs%axpy(1.0_pfdp, lev%Q(Nnodes), 2)
            call this%f_comp(lev%Q(m), t, dt*this%QtilI(Nnodes-m,Nnodes-m+1), this%rhs, lev%index, lev%F(m,2), 2, 2)
            !  Now we need to do the final subtraction for the f3 piece
            call this%rhs%copy(lev%Q(m), 2)
            do n = Nnodes, m+1,-1
               call this%rhs%axpy(dt*this%QtilI(Nnodes-m,Nnodes-n+1), lev%F(n,3), 2)
            end do
            call this%rhs%axpy(-1.0_pfdp, this%I3(m), 2)
            call this%f_comp(lev%Q(m), t, dt*this%QtilI(Nnodes-m,Nnodes-m+1), this%rhs, lev%index, lev%F(m,3), 3, 2)
            call this%f_eval(lev%Q(m), t, lev%index, lev%F(m,1), 1, 2, m, step)
            call this%f_eval(lev%Q(m), t, lev%index, lev%F(m,2), 2, 2, m, step)
         end do
         !call pf_residual(pf, level_index, dt, 2)
         call lev%q0%copy(lev%Q(1), 2)
       end if  ! sweep_p
       if( sweep_p .and. sweep_y ) then
         call pf_residual(pf, level_index, dt, 0)
       else if( sweep_y ) then
         call pf_residual(pf, level_index, dt, 1)
       else if (sweep_p ) then
         call pf_residual(pf, level_index, dt, 2)
      else
         call pf_stop(__FILE__,__LINE__,'invalid sweep')
       end if
       ! done
       call call_hooks(pf, level_index, PF_POST_SWEEP)
    end do ! k=1,nsweeps
  end subroutine misdcQ_oc_sweep
Call graph
misdcq_oc_sweep calls pf_stop, start_timer, pf_residual, call_hooks
start_timer calls mpi_wtime
pf_residual calls start_timer, end_timer, pf_set_resid
call_hooks calls start_timer, end_timer
end_timer calls mpi_wtime