nls_sg_ex – LibPFASST
nls_sg_ex Function
11 statements
Source File
public function nls_sg_ex(t, x, Lx) result(u)
Arguments
Type Intent Optional Attributes Name
real(kind=pfdp), intent(in) :: t
real(kind=pfdp), intent(in) :: x
real(kind=pfdp), intent(in) :: Lx
Return Value real(kind=pfdp)
Called by
Contents
Source Code
nls_sg_ex
Source Code
  function nls_sg_ex(t, x,Lx) result(u)
    real(pfdp), intent(in)  :: t
    real(pfdp), intent(in)  :: x
    real(pfdp), intent(in)  :: Lx
    real(pfdp)  :: u
    real(pfdp) :: sigma,xx
    complex(pfdp) :: ae,dn
    sigma=0.2_pfdp
    xx=(x-Lx*0.5_pfdp)/(sigma*Lx)
    u=exp(-(xx*xx*xx*xx))
  end function nls_sg_ex
Call graph
exact_nls_sg_1d calls nls_sg_ex
exact_nls_sg_3dz calls nls_sg_ex
exact_nls_sg_2dz calls nls_sg_ex
exact_nls_sg_1dz calls nls_sg_ex
exact_nls_sg_3d calls nls_sg_ex
exact_nls_sg_2d calls nls_sg_ex
exact_nls_sg calls exact_nls_sg_1d, exact_nls_sg_3dz, exact_nls_sg_2dz, exact_nls_sg_1dz, exact_nls_sg_3d, exact_nls_sg_2d