pf_apply_mat – LibPFASST
pf_apply_mat Subroutine
26 statements
Source File
public subroutine pf_apply_mat(dst, a, mat, src, zero_first, flags)
Apply a matrix (tmat or rmat) to src and add to dst. Mathematically this is dst= dst + amatsrc Where dst and src are vectors, mat is a matrix, and a is a scalar If the optional variable "zero" is provided and is true, then we compute dst= amatsrc
Arguments
Type Intent Optional Attributes Name
class(pf_encap_t), intent(inout) :: dst(:)
destination vector
real(kind=pfdp), intent(in) :: a
scalar
real(kind=pfdp), intent(in) :: mat(:,:)
matrix
class(pf_encap_t), intent(in) :: src(:)
src vector
logical, intent(in), optional :: zero_first
If true, zero out the the dst variable before computing
integer, intent(in), optional :: flags
Used for choosing which variable to operate on
Local variables
Called by
Contents
Source Code
pf_apply_mat
Source Code
  subroutine pf_apply_mat(dst, a, mat, src, zero_first, flags)
    !! Apply a matrix (tmat or rmat) to src and add to dst.
    !! Mathematically this is
    !!     dst= dst + a*mat*src
    !!  Where dst and src are vectors, mat is a matrix, and a is a scalar
    !!  If the optional variable "zero" is provided and is true, then we compute
    !!     dst=  a*mat*src
    class(pf_encap_t), intent(inout) :: dst(:)       !!  destination vector
    real(pfdp),        intent(in)    :: a            !!  scalar
    real(pfdp),        intent(in)    :: mat(:, :)    !!  matrix
    class(pf_encap_t), intent(in)    :: src(:)       !!  src vector
    logical,           intent(in), optional :: zero_first   !! If true, zero out the the dst variable before computing
    integer,           intent(in), optional :: flags  !! Used for choosing which variable to operate on
    !!  Local variables
    logical :: lzero   !!  local version of input parameter zero
    integer :: which   !!  local version of flags
    integer :: n, m    !!  size of mat
    integer :: i, j    !!  loop variables
    lzero = .true.; if (present(zero_first)) lzero = zero_first
    which = 1;      if(present(flags)) which = flags
    n = SIZE(mat, dim=1)
    m = SIZE(mat, dim=2)
    do i = 1, n
      if (lzero) call dst(i)%setval(0.0_pfdp, flags)
      do j = 1, m
         if (abs(a*mat(i, j)) /= 0.0_pfdp) then
            call dst(i)%axpy(a * mat(i, j), src(j), flags)
         end if
      end do
    end do
  end subroutine pf_apply_mat
Call graph
restrict_ts_integral calls pf_apply_mat
restrict_ts calls pf_apply_mat
interpolate_time_space calls pf_apply_mat
pf_v_cycle_oc calls interpolate_time_space, restrict_time_space_fas
pf_vcycle_pysdc calls interpolate_time_space, restrict_time_space_fas
restrict_time_space_fas calls restrict_ts_integral, restrict_ts
pf_predictor_oc calls interpolate_time_space, restrict_time_space_fas
pf_predictor calls interpolate_time_space, restrict_time_space_fas
pf_vcycle calls interpolate_time_space, restrict_time_space_fas
pf_block_run calls pf_vcycle_pysdc, pf_predictor, pf_vcycle
pf_pfasst_block_oc calls pf_v_cycle_oc, pf_predictor_oc
pf_pfasst_run calls pf_block_run