pf_block_run – LibPFASST
pf_block_run Subroutine
83 statements
Source File
public subroutine pf_block_run(pf, q0, dt, nsteps, qend, flags)
PFASST controller for block mode When starting a new block, broadcast new initial conditions to all procs For initial block, this is done when initial conditions are set Reset some flags Pack away your last solution Everyone resets their q0 Just stick qend in q0 Update the step and t0 variables for new block Call the predictor to get an initial guess on all levels and all processors
Start the loops over SDC sweeps
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
class(pf_encap_t), intent(in) :: q0
real(kind=pfdp), intent(inout) :: dt
integer, intent(inout) :: nsteps
class(pf_encap_t), intent(inout), optional :: qend
integer, intent(in), optional :: flags(:)
Calls
Called by
Contents
Source Code
pf_block_run
Source Code
  subroutine pf_block_run(pf, q0, dt, nsteps, qend,flags)
    type(pf_pfasst_t), intent(inout), target   :: pf
    class(pf_encap_t), intent(in   )           :: q0
    real(pfdp),        intent(inout)           :: dt
    integer,           intent(inout)           :: nsteps
    class(pf_encap_t), intent(inout), optional :: qend
    integer,           intent(in   ), optional :: flags(:)
    class(pf_level_t), pointer :: lev  !!  pointer to the one level we are operating on
    integer                   :: j, k
    integer                   :: nblocks !!  The number of blocks of steps to do
    integer                   :: nproc   !!  The number of processors being used
    integer                   :: level_index_c !!  Coarsest level in V (Lambda)-cycle
    integer                   :: level_max_depth !!  Finest level in V-cycle
    pf%state%dt      = dt
    pf%state%proc    = pf%rank+1
    pf%state%step    = pf%rank
    pf%state%t0      = pf%state%step * dt
    ! set finest level to visit in the following run
    pf%state%finest_level = pf%nlevels
    !  pointer to finest  level to start
    lev => pf%levels(pf%state%finest_level)
    !  Stick the initial condition into q0 (will happen on all processors)
    call lev%q0%copy(q0, flags=0)
    nproc = pf%comm%nproc
    nblocks = nsteps/nproc
    !  Decide what the coarsest level in the V-cycle is
    level_index_c=1
    if (.not. pf%Vcycle)     level_index_c=pf%state%finest_level
    do k = 1, nblocks   !  Loop over blocks of time steps
       if (pf%save_timings > 1) call pf_start_timer(pf, T_BLOCK)
       ! print *,'Starting  step=',pf%state%step,'  block k=',k
       ! Each block will consist of
       !  0.  choose time step
       !  1.  predictor
       !  2.  Vcycle until max iterations, or tolerances met
       !  3.  Move solution to next block
       !  Reset some flags
       !>  When starting a new block, broadcast new initial conditions to all procs
       !>  For initial block, this is done when initial conditions are set
       !> Reset some flags
       pf%state%iter    = -1
       pf%state%itcnt   = 0
       pf%state%mysteps = 0
       pf%state%status  = PF_STATUS_PREDICTOR
       pf%state%pstatus = PF_STATUS_PREDICTOR
       pf%comm%statreq  = -66
       pf%state%pfblock = k
       pf%state%sweep = 1
       if (k > 1) then
          if (nproc > 1)  then
             call lev%qend%pack(lev%send)    !!  Pack away your last solution
             call pf_broadcast(pf, lev%send, lev%mpibuflen, pf%comm%nproc-1)
             call lev%q0%unpack(lev%send)    !!  Everyone resets their q0
          else
             call lev%q0%copy(lev%qend, flags=0)    !!  Just stick qend in q0
          end if
          !>  Update the step and t0 variables for new block
          pf%state%step = pf%state%step + pf%comm%nproc
          pf%state%t0   = pf%state%step * dt
       end if
       !> Call the predictor to get an initial guess on all levels and all processors
       call pf_predictor(pf, pf%state%t0, dt, flags)
       !>  Start the loops over SDC sweeps
       pf%state%iter = 0
       call pf_set_resid(pf,lev%index,lev%residual)
       call call_hooks(pf, -1, PF_POST_ITERATION)
       do j = 1, pf%niters
          if (pf%save_timings > 1) call pf_start_timer(pf, T_ITERATION)
          call call_hooks(pf, -1, PF_PRE_ITERATION)
          pf%state%iter = j
          !  Do a V-cycle
          if (pf%use_pySDC_V) then
             call pf_Vcycle_pySDC(pf,k,pf%state%t0,dt,level_index_c, pf%state%finest_level)
          else
             call pf_Vcycle(pf, k, pf%state%t0, dt, level_index_c, pf%state%finest_level)
          end if
          !  Check for convergence
          call pf_check_convergence_block(pf, pf%state%finest_level, send_tag=1111*k+j)
          call call_hooks(pf, -1, PF_POST_ITERATION)
          if (pf%save_timings > 1) call pf_stop_timer(pf, T_ITERATION)
          !  If we are converged, exit block (can do one last sweep if desired)
          if (pf%state%status == PF_STATUS_CONVERGED)  then
             if (pf%sweep_at_conv) then
                if (pf%debug) print*,  'DEBUG --',pf%rank,'sweep at convergence'
                call pf%levels(pf%nlevels)%ulevel%sweeper%sweep(pf, pf%nlevels, pf%state%t0, dt, 1)
             end if
             call call_hooks(pf, -1, PF_POST_CONVERGENCE)
             call pf_set_iter(pf,j)
             exit
          end if
       end do  !  Loop over the iteration in this bloc
       if (pf%nlevels .gt. 1) then
          if (pf%debug) print*,  'DEBUG --',pf%rank,'sweep after iterations on fine'
          call pf%levels(pf%nlevels)%ulevel%sweeper%sweep(pf, pf%nlevels, pf%state%t0, dt, 1)
       end if
       if (pf%save_timings > 1) call pf_stop_timer(pf, T_BLOCK)
       call call_hooks(pf, -1, PF_POST_BLOCK)
    end do !  Loop over the blocks
    call call_hooks(pf, -1, PF_POST_ALL)
    !  Grab the last solution for return (if wanted)
    if (present(qend)) then
       call qend%copy(lev%qend, flags=0)
    end if
  end subroutine pf_block_run
Call graph
pf_block_run calls pf_vcycle_pysdc, pf_set_resid, pf_check_convergence_block, call_hooks, pf_broadcast, pf_predictor, pf_set_iter, pf_vcycle
pf_vcycle_pysdc calls interpolate_time_space, restrict_time_space_fas, pf_residual, interpolate_q0, pf_delta_q0, pf_send, pf_post, pf_recv
pf_check_convergence_block calls call_hooks, pf_send_status, pf_check_residual
pf_broadcast calls pf_stop
pf_predictor calls call_hooks, interpolate_time_space, restrict_time_space_fas, pf_residual, pf_send, pf_recv
pf_vcycle calls interpolate_time_space, restrict_time_space_fas, pf_residual, interpolate_q0, pf_delta_q0, pf_send, pf_post, pf_recv
interpolate_time_space calls call_hooks, pf_apply_mat
restrict_time_space_fas calls call_hooks, restrict_ts, restrict_ts_integral
pf_residual calls pf_set_resid
pf_send_status calls pf_stop
interpolate_q0 calls call_hooks
pf_delta_q0 calls pf_set_delta_q0
pf_send calls pf_stop
pf_post calls pf_stop
pf_recv calls pf_stop_timer, pf_start_timer
restrict_ts calls pf_apply_mat
restrict_ts_integral calls pf_apply_mat
pf_pfasst_run calls pf_block_run