pf_dump_results – LibPFASST
pf_dump_results Subroutine
17 statements
Source File
public subroutine pf_dump_results(pf)
Subroutine to write out run parameters
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout) :: pf
Calls
Called by
Contents
Source Code
pf_dump_results
Source Code
  subroutine pf_dump_results(pf)
    type(pf_pfasst_t), intent(inout)           :: pf
    integer :: level_index
    if (pf%save_residuals) then
       do level_index = 1,pf%nlevels
          call  dump_resids(pf%results(level_index))
       end do
    end if
    if (pf%save_errors) then
       do level_index = 1,pf%nlevels
          call  dump_errors(pf%results(level_index))
       end do
    end if
    if (pf%save_timings) then
       call  dump_timings(pf)
    end if
end subroutine pf_dump_results
Call graph
pf_dump_results calls dump_resids, dump_timings, dump_errors
dump_timings calls timer_names
pf_parareal_run calls pf_dump_results
pf_pfasst_run calls pf_dump_results