pf_delta_q0 – LibPFASST
pf_delta_q0 Subroutine
9 statements
Source File
public subroutine pf_delta_q0(pf, level_index)
Assign level pointer
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
PFASST structure
integer, intent(in) :: level_index
level on which to sweep
Calls
Called by
Contents
Source Code
pf_delta_q0
Source Code
  subroutine pf_delta_q0(pf,level_index)
    type(pf_pfasst_t), intent(inout),target :: pf    !!  PFASST structure
    integer,           intent(in)    :: level_index  !!  level on which to sweep
    class(pf_level_t), pointer :: lev  !!  Level on which to spread
    lev => pf%levels(level_index)   !!  Assign level pointer
    call lev%delta_q0%axpy(-1.0_pfdp,lev%q0)
    lev%max_delta_q0=lev%delta_q0%norm()
    call pf_set_delta_q0(pf,level_index,lev%max_delta_q0)
  end subroutine pf_delta_q0
Call graph
pf_delta_q0 calls pf_set_delta_q0
pf_vcycle calls pf_delta_q0
pf_vcycle_pysdc calls pf_delta_q0
pf_block_run calls pf_vcycle, pf_vcycle_pysdc
pf_pfasst_run calls pf_block_run