pf_generic_evaluate_all – LibPFASST
pf_generic_evaluate_all Subroutine
13 statements
Source File
public subroutine pf_generic_evaluate_all(this, pf, level_index, t, flags, step)
Generic evaluate all Each sweeper can define its own evaluate_all or use this generic one Assign level pointer
Arguments
Type Intent Optional Attributes Name
class(pf_sweeper_t), intent(in) :: this
type(pf_pfasst_t), intent(inout), target :: pf
integer, intent(in) :: level_index
real(kind=pfdp), intent(in) :: t(:)
integer, intent(in), optional :: flags
integer, intent(in), optional :: step
Called by
Contents
Source Code
pf_generic_evaluate_all
Source Code
  subroutine pf_generic_evaluate_all(this, pf, level_index, t, flags, step)
    class(pf_sweeper_t), intent(in)  :: this
    type(pf_pfasst_t),   intent(inout),target :: pf
    integer,             intent(in)    :: level_index
    real(pfdp),        intent(in)    :: t(:)
    integer, optional, intent(in)    :: flags, step
    integer :: m
    class(pf_level_t), pointer :: lev    !!  points to current level
    lev => pf%levels(level_index)   !!  Assign level pointer
!     which = 1
!     if(present(flags)) which = flags
!     mystep = 1
!     if(present(step)) mystep = step
    do m = 1, lev%nnodes
       call lev%ulevel%sweeper%evaluate(pf,level_index, t(m), m, flags=flags, step=step)
    end do
  end subroutine pf_generic_evaluate_all
Call graph
misdc_evaluate_all calls pf_generic_evaluate_all
magpicard_evaluate_all calls pf_generic_evaluate_all
exp_evaluate_all calls pf_generic_evaluate_all
imex_evaluate_all calls pf_generic_evaluate_all
amisdc_evaluate_all calls pf_generic_evaluate_all
verlet_evaluate_all calls pf_generic_evaluate_all
misdcq_evaluate_all calls pf_generic_evaluate_all