pf_generic_spreadq0 – LibPFASST
pf_generic_spreadq0 Subroutine
17 statements
Source File
public subroutine pf_generic_spreadq0(this, pf, level_index, t0)
Generic routine to spread initial conditions Each sweeper can define its own spreadq0 or use this generic one Assign level pointer
Arguments
Type Intent Optional Attributes Name
class(pf_sweeper_t), intent(in) :: this
type(pf_pfasst_t), intent(inout), target :: pf
PFASST structure
integer, intent(in) :: level_index
level on which to sweep
real(kind=pfdp), intent(in) :: t0
time at beginning of interval
Called by
Contents
Source Code
pf_generic_spreadq0
Source Code
  subroutine pf_generic_spreadq0(this,pf,level_index, t0)
    class(pf_sweeper_t), intent(in)  :: this
    type(pf_pfasst_t), intent(inout),target :: pf    !!  PFASST structure
    integer,           intent(in)    :: level_index  !!  level on which to sweep
    real(pfdp),       intent(in)    :: t0    !!  time at beginning of interval
    integer :: m, p
    class(pf_level_t), pointer :: lev  !!  Level on which to spread
    lev => pf%levels(level_index)   !!  Assign level pointer
    !  Stick initial condition into first node slot
    call lev%Q(1)%copy(lev%q0)
    !  Evaluate F at first spot
    call lev%ulevel%sweeper%evaluate(pf,level_index, t0, 1)
    ! Spread F and solution to all nodes
    do m = 2, lev%nnodes
       call lev%Q(m)%copy(lev%Q(1))
       do p = 1, lev%ulevel%sweeper%npieces
         call lev%F(m,p)%copy(lev%F(1,p))
       end do
    end do
  end subroutine pf_generic_spreadq0
Call graph
imex_spreadq0 calls pf_generic_spreadq0
verlet_spreadq0 calls pf_generic_spreadq0
misdcq_spreadq0 calls pf_generic_spreadq0
magpicard_spreadq0 calls pf_generic_spreadq0
exp_spreadq0 calls pf_generic_spreadq0