pf_generic_residual – LibPFASST
pf_generic_residual Subroutine
36 statements
Source File
public subroutine pf_generic_residual(this, pf, level_index, dt, flags)
Generic residual Each sweeper can define its own residual, or use this generic one This routine is in the "Q" form, so the residual approximates R(m)=y(t_n) + \int_{t_n}^t_m f(y,s) ds - y(t_m) Compute the integral of F from t_n to t_m at each node
add tau if it exists subtract out the solution value
Arguments
Type Intent Optional Attributes Name
class(pf_sweeper_t), intent(in) :: this
type(pf_pfasst_t), intent(inout), target :: pf
integer, intent(in) :: level_index
real(kind=pfdp), intent(in) :: dt
integer, intent(in), optional :: flags
Called by
Contents
Source Code
pf_generic_residual
Source Code
  subroutine pf_generic_residual(this, pf,level_index, dt, flags)
    class(pf_sweeper_t), intent(in)  :: this
    type(pf_pfasst_t), target,  intent(inout) :: pf
    integer,              intent(in)    :: level_index
    real(pfdp),        intent(in)    :: dt
    integer,  intent(in), optional  :: flags
    integer :: m
    type(pf_level_t), pointer :: lev
    lev=>pf%levels(level_index)
    !>  Compute the integral of F from t_n to t_m at each node
    call lev%ulevel%sweeper%integrate(pf,level_index, lev%Q, lev%F, dt, lev%I, flags)
    !> add tau if it exists
    if (lev%index < pf%state%finest_level) then
       do m = 1, lev%nnodes-1
          call lev%I(m)%axpy(1.0_pfdp, lev%tauQ(m), flags)
       end do
    end if
    !> subtract out the solution value
    if (present(flags)) then
      do m = 1, lev%nnodes-1
        if( (flags .eq. 0) .or. (flags .eq. 1) ) then
          call lev%R(m)%copy(lev%I(m), 1)
          call lev%R(m)%axpy(1.0_pfdp, lev%Q(1), 1)
          call lev%R(m)%axpy(-1.0_pfdp, lev%Q(m+1), 1)
        end if
        if( (flags .eq. 0) .or. (flags .eq. 2) ) then
          call lev%R(m)%copy(lev%I(m), 2)
          call lev%R(m)%axpy(1.0_pfdp, lev%Q(lev%nnodes), 2)
          call lev%R(m)%axpy(-1.0_pfdp, lev%Q(m), 2)
        end if
      end do
    else
      do m = 1, lev%nnodes-1
        call lev%R(m)%copy(lev%I(m))
        call lev%R(m)%axpy(1.0_pfdp, lev%Q(1))
        call lev%R(m)%axpy(-1.0_pfdp, lev%Q(m+1))
      end do
    end if
  end subroutine pf_generic_residual
Call graph
misdc_residual calls pf_generic_residual
amisdc_residual calls pf_generic_residual
misdcq_residual calls pf_generic_residual
imex_residual calls pf_generic_residual