pf_init_sdcmats – LibPFASST
pf_init_sdcmats Subroutine
27 statements
Source File
public subroutine pf_init_sdcmats(pf, SDCmats, nnodes, nflags)
Uses
pf_mod_utils
Initialize the sdcmats type with the correct nodes and quadrature matrices Decide what the base integration type is
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(in) :: pf
PFASST structure
type(pf_sdcmats_t), intent(inout) :: SDCmats
integer, intent(in) :: nnodes
integer, intent(inout) :: nflags(nnodes)
Calls
Called by
Contents
Source Code
pf_init_sdcmats
Source Code
  subroutine pf_init_sdcmats(pf,SDCmats,nnodes,nflags)
    use pf_mod_utils
    type(pf_pfasst_t), intent(in) :: pf    !!  PFASST structure
     type(pf_sdcmats_t), intent(inout) :: SDCmats
     integer, intent(in) :: nnodes  ! Number of ndoes
     integer,    intent(inout) :: nflags(nnodes)
     integer :: ierr
     integer :: nnodes0
     !  Copy some info
     SDCmats%nnodes=nnodes
     SDCmats%qtype=pf%qtype
     SDCmats%use_proper_nodes=pf%use_proper_nodes
     SDCmats%use_composite_nodes=pf%use_composite_nodes
     SDCmats%use_no_left_q=pf%use_no_left_q
     !> Decide what the base integration type is
     if (SDCmats%use_composite_nodes) then
        nnodes0=pf%levels(1)%nnodes  !  Will use the coarsest quadrature rule in composite
     else
        nnodes0=pf%levels(pf%nlevels)%nnodes  ! Will use the
     end if
     !  Allocate nodes and collocation matrices
     allocate(SDCmats%qnodes(nnodes),stat=ierr)
     if (ierr /= 0) call pf_stop(__FILE__, &
          __LINE__,"allocate error qnodes")
     allocate(SDCmats%Qmat(nnodes-1,nnodes),stat=ierr)
     if (ierr /= 0) call pf_stop(__FILE__,__LINE__, "allocate error Qmat")
     allocate(SDCmats%Smat(nnodes-1,nnodes),stat=ierr)
     if (ierr /= 0) call pf_stop(__FILE__,__LINE__, "allocate error Smat")
     !  Make the nodes and collocation matrices
     call pf_quadrature(SDCmats%qtype, nnodes, nnodes0, &
          SDCmats%qnodes, nflags, SDCmats%Smat, SDCmats%Qmat, &
          SDCmats%use_proper_nodes,SDCmats%use_composite_nodes,SDCmats%use_no_left_q)
     !  Make the substepping matrices
     call pf_make_matrices(SDCmats)
  end subroutine pf_init_sdcmats
Call graph
pf_init_sdcmats calls pf_make_matrices, pf_quadrature
pf_make_matrices calls myluq
pf_quadrature calls sdc_qnodes, pf_stop, sdc_qmats
sdc_qnodes calls pf_stop, poly_legendre, poly_diff, poly_roots
myluq calls pf_stop
sdc_qmats calls poly_int, not_proper, poly_eval
poly_roots calls qsort, poly_eval_complex
poly_eval calls poly_eval, poly_eval_complex
pf_level_setup calls pf_init_sdcmats
pf_pfasst_setup calls pf_level_setup