pf_level_setup – LibPFASST
pf_level_setup Subroutine
56 statements
Source File
public subroutine pf_level_setup(pf, level_index)
Uses
pf_mod_quadrature
Setup (allocate) PFASST level If the level is already setup, calling this again will allocate (or deallocate) tauQ appropriately. Assign level pointer
do some sanity checks (re)allocate tauQ skip the rest if we're already allocated allocate flat buffers for send, and recv allocate nodes, flags, and integration matrices initialize sweeper Allocate and compute all the matrices Allocate space for solutions
allocate solution and function arrays for sdc sweepers Allocate space for residual and things need for sdc and rk
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
Main pfasst structure
integer, intent(in) :: level_index
level to set up
Calls
Called by
Contents
Source Code
pf_level_setup
Source Code
  subroutine pf_level_setup(pf, level_index)
    use pf_mod_quadrature
    type(pf_pfasst_t), intent(inout),target :: pf   !!  Main pfasst structure
    integer,           intent(in)    :: level_index  !!  level to set up
    class(pf_level_t),  pointer :: lev  !!  Level to set up
    integer :: mpibuflen, nnodes, npieces, nnodes0
    integer :: i,ierr
    lev => pf%levels(level_index)   !!  Assign level pointer
    !> do some sanity checks
    mpibuflen  = lev%mpibuflen
    if (mpibuflen <= 0) call pf_stop(__FILE__,__LINE__,'bad value for mpibulen=',mpibuflen)
    nnodes = lev%nnodes
    if (nnodes <= 0) call pf_stop(__FILE__,__LINE__,'bad value for nnodes=',nnodes)
    lev%residual = -1.0_pfdp
    !> (re)allocate tauQ
    if ((lev%index < pf%nlevels) .and. (.not. allocated(lev%tauQ))) then
       call lev%ulevel%factory%create_array(lev%tauQ, nnodes-1, lev%index,  lev%lev_shape)
    end if
    !> skip the rest if we're already allocated
    if (lev%allocated) return
    lev%allocated = .true.
    !> allocate flat buffers for send, and recv
    allocate(lev%send(mpibuflen),stat=ierr)
    if (ierr /= 0) call pf_stop(__FILE__,__LINE__,"allocate fail")
    allocate(lev%recv(mpibuflen),stat=ierr)
    if (ierr /= 0) call pf_stop(__FILE__,__LINE__,"allocate fail")
    !> allocate nodes, flags, and integration matrices
    allocate(lev%nodes(nnodes),stat=ierr)
    if (ierr /= 0) call pf_stop(__FILE__,__LINE__,"allocate fail")
    allocate(lev%nflags(nnodes),stat=ierr)
    if (ierr /= 0) call pf_stop(__FILE__,__LINE__,"allocate fail")
    lev%nflags=0
    !>  initialize sweeper
    if (pf%use_sdc_sweeper) then
       !>  Allocate and compute all the matrices
       allocate(lev%sdcmats,stat=ierr)
       if (ierr /= 0) call pf_stop(__FILE__,__LINE__,"allocate error sdcmats")
       call pf_init_sdcmats(pf,lev%sdcmats, nnodes,lev%nflags)
       lev%nodes = lev%sdcmats%qnodes
       lev%ulevel%sweeper%use_LUq=pf%use_LUq
       call lev%ulevel%sweeper%initialize(pf,level_index)
    end if
    if (pf%use_rk_stepper)  call lev%ulevel%stepper%initialize(pf,level_index)
    !>  Allocate space for solutions
    call lev%ulevel%factory%create_array(lev%Q, nnodes, lev%index,  lev%lev_shape)
    !> allocate solution and function arrays for sdc sweepers
    if (pf%use_sdc_sweeper) then
       npieces = lev%ulevel%sweeper%npieces
       call lev%ulevel%factory%create_array(lev%I, nnodes-1, lev%index,  lev%lev_shape)
       !  Space for function values
       call lev%ulevel%factory%create_array(lev%Fflt, nnodes*npieces, lev%index,  lev%lev_shape)
       do i = 1, nnodes*npieces
          call lev%Fflt(i)%setval(0.0_pfdp, 0)
       end do
       lev%F(1:nnodes,1:npieces) => lev%Fflt
       !  Need space for old function values in im sweepers
       call lev%ulevel%factory%create_array(lev%pFflt, nnodes*npieces, lev%index, lev%lev_shape)
       lev%pF(1:nnodes,1:npieces) => lev%pFflt
       if (lev%index < pf%nlevels) then
          call lev%ulevel%factory%create_array(lev%pQ, nnodes, lev%index,  lev%lev_shape)
       end if
    end if
    !>  Allocate space for residual and things need for sdc and rk
    call lev%ulevel%factory%create_array(lev%R, nnodes-1, lev%index,  lev%lev_shape)
    call lev%ulevel%factory%create_single(lev%qend, lev%index,   lev%lev_shape)
    call lev%ulevel%factory%create_single(lev%q0, lev%index,   lev%lev_shape)
    call lev%ulevel%factory%create_single(lev%delta_q0, lev%index,   lev%lev_shape)
  end subroutine pf_level_setup
Call graph
pf_level_setup calls pf_init_sdcmats
pf_init_sdcmats calls pf_make_matrices, pf_quadrature
pf_make_matrices calls myluq
pf_quadrature calls pf_stop, sdc_qnodes, sdc_qmats
myluq calls pf_stop
sdc_qnodes calls pf_stop, poly_roots, poly_diff, poly_legendre
sdc_qmats calls not_proper, poly_eval, poly_int
poly_roots calls poly_eval_complex, qsort
poly_eval calls poly_eval, poly_eval_complex
pf_pfasst_setup calls pf_level_setup