pf_parareal_predictor – LibPFASST
pf_parareal_predictor Subroutine
37 statements
Source File
public subroutine pf_parareal_predictor(pf, t0, dt, flags)
The parareal predictor does a serial integration on the coarse level followed by a fine integration if there is a fine level Step 1. Getting the initial condition on the coarsest level
Step 2. Do coarse level integration, no communication necessary
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
PFASST main data structure
real(kind=pfdp), intent(in) :: t0
Initial time of this processor
real(kind=pfdp), intent(in) :: dt
time step
integer, intent(in), optional :: flags(:)
User defined flags
Calls
Called by
Contents
Source Code
pf_parareal_predictor
Source Code
  subroutine pf_parareal_predictor(pf, t0, dt, flags)
    type(pf_pfasst_t), intent(inout), target :: pf     !! PFASST main data structure
    real(pfdp),        intent(in   )         :: t0     !! Initial time of this processor
    real(pfdp),        intent(in   )         :: dt     !! time step
    integer,           intent(in   ), optional :: flags(:)  !!  User defined flags
    class(pf_level_t), pointer :: c_lev
    class(pf_level_t), pointer :: f_lev     !!
    integer                   :: k,n               !!  Loop indices
    integer                   :: nsteps_c,nsteps_f    !!  Number of RK  steps
    integer                   :: level_index     !!  Local variable for looping over levels
    real(pfdp)                :: t0k             !!  Initial time at time step k
    pf%state%iter = 0
    call call_hooks(pf, 1, PF_PRE_PREDICTOR)
    call start_timer(pf, TPREDICTOR)
    !  This is for one two levels only or one if only RK is done
    c_lev => pf%levels(1)
    f_lev => pf%levels(pf%state%finest_level)
    if (pf%debug) print*, 'DEBUG --', pf%rank, 'beginning parareal predictor'
    !! Step 1. Getting the initial condition on the coarsest level
    if (pf%state%finest_level > 1) then
       if (pf%q0_style < 2) then  !  Copy coarse
          call c_lev%q0%copy(f_lev%q0)
       end if
    end if
    level_index = 1
    !!
    !! Step 2. Do coarse level integration, no communication necessary
    nsteps_c= c_lev%ulevel%stepper%nsteps  !  Each processor integrates alone
    do n=1,pf%rank+1
       if (n .gt. 1) call c_lev%q0%copy(c_lev%qend)
       t0k      = dt*real(n-1,pfdp)
       call c_lev%ulevel%stepper%do_n_steps(pf, 1, t0k, c_lev%q0,c_lev%qend,dt, nsteps_c)
    end do
    ! Save the coarse level value
    call c_lev%Q(2)%copy(c_lev%qend, flags=0)
    call end_timer(pf, TPREDICTOR)
    pf%state%iter   = 1
    pf%state%status = PF_STATUS_ITERATING
    pf%state%pstatus = PF_STATUS_ITERATING
    if (pf%debug) print*,  'DEBUG --', pf%rank, 'ending predictor'
    call call_hooks(pf, -1, PF_POST_PREDICTOR)
  end subroutine pf_parareal_predictor
Call graph
pf_parareal_predictor calls call_hooks, start_timer, end_timer
call_hooks calls start_timer, end_timer
start_timer calls mpi_wtime
end_timer calls mpi_wtime
pf_parareal_block_run calls pf_parareal_predictor
pf_parareal_run calls pf_parareal_block_run