pf_petscVec_build – LibPFASST
pf_petscVec_build Subroutine
23 statements
Source File
public subroutine pf_petscVec_build(q, shape_in)
Uses
pf_mod_comm_mpi
Subroutine to allocate the array and set the size parameters
Arguments
Type Intent Optional Attributes Name
class(pf_encap_t), intent(inout) :: q
integer, intent(in) :: shape_in(:)
Calls
Called by
Contents
Source Code
pf_petscVec_build
Source Code
  subroutine pf_petscVec_build(q, shape_in)
    use pf_mod_comm_mpi
    class(pf_encap_t), intent(inout) :: q
    integer,           intent(in   ) :: shape_in(:)
    integer nn,psize,rank,ierr
    select type (q)
    class is (pf_petscVec_t)
       call VecCreate(PETSC_COMM_WORLD,q%petscVec,ierr);CHKERRQ(ierr)
       call VecSetSizes(q%petscVec,PETSC_DECIDE,shape_in(1),ierr);CHKERRQ(ierr)
       call VecSetFromOptions(q%petscVec,ierr);CHKERRQ(ierr)
       call VecGetLocalSize(q%petscVec,psize,ierr);CHKERRQ(ierr)
       call mpi_comm_rank(PETSC_COMM_WORLD, rank,ierr);CHKERRQ(ierr)
       allocate(q%arr_shape(SIZE(shape_in)),stat=ierr)
       if (ierr /=0) call pf_stop(__FILE__,__LINE__,'allocate fail, error=',ierr)
       q%ndim   = SIZE(shape_in)
       q%arr_shape = shape_in
    end select
  end subroutine pf_petscVec_build
Call graph
pf_petscvec_build calls veccreate, vecgetlocalsize, mpi_comm_rank, vecsetfromoptions, chkerrq
pf_petscvec_create_single calls pf_petscvec_build