pf_print_options – LibPFASST
pf_print_options Subroutine
164 statements
Source File
public subroutine pf_print_options(pf, un_opt, show_mats_opt, json_opt)
Subroutine to write out run parameters
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout) :: pf
integer, intent(in), optional :: un_opt
logical, intent(in), optional :: show_mats_opt
logical, intent(in), optional :: json_opt
Calls
Contents
Source Code
pf_print_options
Source Code
  subroutine pf_print_options(pf, un_opt, show_mats_opt,json_opt)
    type(pf_pfasst_t), intent(inout)           :: pf
    integer,           intent(in   ), optional :: un_opt
    logical,           intent(in   ), optional :: show_mats_opt
    logical,           intent(in   ), optional :: json_opt
    integer :: un = 6
    logical :: show_mats = .FALSE.
    logical :: dump_json = .TRUE.
    integer :: l, i,istat,system
    character(8)   :: date
    character(10)  :: time
    character(len = 128) :: fname  !!  output file name for residuals
    character(len = 128) :: datpath  !!  path to output files
    if (pf%rank /= 0) return
    if (present(un_opt)) un = un_opt
    write(un,*) '================================================'
    write(un,*) '----------- LibPFASST Parameters ---------------'
    call date_and_time(date=date, time=time)
    write(un,*) 'date:        ', date
    write(un,*) 'time:        ', time
    if(pf%use_sdc_sweeper) then
       write(un,*) 'method:        ',' PFASST'
    else
       write(un,*) 'method:        ',' parareal'
    end if
    write(un,*) 'double precision:   ', pfdp   ,'  bytes'
    write(un,*) 'quad precision:   ', pfqp   ,'  bytes'
    write(un,*) 'Output directory: ', trim(pf%outdir)
    write(un,*) 'Nprocs:      ', pf%comm%nproc, '! number of pfasst "time" processors'
    write(un,*) 'Nlevels:     ', pf%nlevels, '! number of levels'
    if (pf%use_sdc_sweeper) then
       if (pf%comm%nproc == 1) then
          write(un,*) '            ', '             ', ' ! since 1 time proc is being used, this is a serial sdc run'
       else
          write(un,*) '            ', '             ', ' ! since >1 time procs are being used, this is a parallel pfasst run'
       end if
       write(un,*) 'Niters:      ', pf%niters, '! maximum number of sdc/pfasst iterations'
       write(un,*) 'Nnodes:      ', pf%levels(1:pf%nlevels)%nnodes, '! number of sdc nodes per level'
       write(un,*) 'Nsweeps:     ', pf%levels(1:pf%nlevels)%nsweeps, '! number of sdc sweeps performed per visit to each level'
       write(un,*) 'Nsweeps_pred:     ', pf%levels(1:pf%nlevels)%nsweeps_pred, '! number of sdc sweeps in predictor'
       select case(pf%qtype)
       case (SDC_GAUSS_LEGENDRE)
          write(un,*) 'qtype:',pf%qtype, '! Gauss Legendre nodes are used'
       case (SDC_GAUSS_LOBATTO)
          write(un,*) 'qtype:',pf%qtype,'! Gauss Lobatto nodes are used'
       case (SDC_GAUSS_RADAU)
          write(un,*) 'qtype:',pf%qtype,'! Gauss Radau nodes are used'
       case (SDC_CLENSHAW_CURTIS)
          write(un,*) 'qtype:',pf%qtype,'! Clenshaw Curtis nodes are used'
       case (SDC_UNIFORM)
          write(un,*) 'qtype:', pf%qtype,'! Uniform  nodes are used'
       case (SDC_CHEBYSHEV)
          write(un,*) 'qtype:', pf%qtype,'! Chebyshev  nodes are used'
       case DEFAULT
          call pf_stop(__FILE__,__LINE__,'Bad case in SELECT',pf%qtype)
       end select
       if (pf%use_Luq) then
          write(un,*) 'Implicit matrix is LU  '
       else
          write(un,*) 'Implicit matrix is backward Euler  '
       end if
       if (pf%use_Sform) then
          write(un,*) 'The Smat form of stepping is being done'
       else
          write(un,*) 'The Qmat form of stepping is being done'
       end if
       if (present(show_mats_opt)) show_mats=show_mats_opt
       if (show_mats) then
          do l = 1, pf%nlevels
             print *, "Level", l
             print *, "-----------------"
             print *, "  nodes"
             print *, pf%levels(l)%nodes
             print *, "  Q"
             do i = 1, pf%levels(l)%nnodes-1
                print *, pf%levels(l)%sdcmats%qmat(i,:)
             end do
          end do
       end if
       if (pf%use_proper_nodes)  write(un,*) 'Using proper node nesting'
       if (pf%use_composite_nodes)  write(un,*) 'Using composite node nesting'
       if (pf%use_no_left_q)  write(un,*) ' Skipping left end point in quadruture rule '
       write(un,*) 'taui0:     ',   pf%taui0, '! cutoff for tau correction'
       write(un,*) 'abs_res_tol:', pf%abs_res_tol, '! absolute residual tolerance: '
       write(un,*) 'rel_res_tol:', pf%rel_res_tol, '! relative residual tolerance: '
       write(un,*) 'mpibuflen:   ', pf%levels(1:pf%nlevels)%mpibuflen, '! size of data send between time steps'
       if (pf%Vcycle) then
          write(un,*) 'V-cycling is on'
       else
          write(un,*) 'V-cycling is off, fine level is pipelining'
       end if
       if (pf%rk_pred) then
          write(un,*) 'Runge-Kutta used for predictor'
       else
          if (pf%pipeline_pred) then
             write(un,*) 'Predictor pipelining is ON    '
          else
             write(un,*) 'Predictor pipelining is OFF    '
          end if
          if (pf%PFASST_pred) then
             write(un,*) 'PFASST Predictor style  '
          else
             write(un,*) 'Serial Predictor style  '
          end if
       endif
       if (pf%debug) write(un,*) 'Debug mode is on '
    end if
    if (present(json_opt)) dump_json=json_opt
    if (dump_json) then
       ! Create a json file of all the pfasst parameters
       istat= system('mkdir -p dat')
       if (istat .ne. 0) call pf_stop(__FILE__,__LINE__, "Cannot make directory in pf_print_options")
       istat= system('mkdir -p dat/' // trim(pf%outdir))
       if (istat .ne. 0) call pf_stop(__FILE__,__LINE__, "Cannot make directory in pf_print_options")
       datpath= 'dat/' // trim(pf%outdir)
       fname=trim(datpath) // '/pfasst_params.json'
       un=321
       open(unit=un, file=trim(fname), form='formatted')
       write(un,*) '{'
       if(pf%use_sdc_sweeper) then
          write(un,*) '      "method" :  "PFASST",'
       else
          write(un,*) '      "method" :  "parareal",'
       end if
       write(un,123)  '"use_rk_stepper" :',     convert_logical(pf%use_rk_stepper), ','
       write(un,123)  '"use_sdc_sweeper" :',     convert_logical(pf%use_sdc_sweeper), ','
       write(un,122)  '"nproc" :',       pf%comm%nproc, ','
       write(un,122)  '"nlevels" :',     pf%nlevels, ','
       write(un,122)  '"niters" :',      pf%niters, ','
       write(un,123)  '"nnodes" :',      adjustr(convert_int_array(pf%nnodes(1:pf%nlevels),pf%nlevels)), ','
       write(un,122)  '"q0_style" :',    pf%q0_style, ','
       write(un,123)  '"nsweeps" :',     adjustr(convert_int_array(pf%nsweeps(1:pf%nlevels),pf%nlevels)), ','
       if(pf%use_sdc_sweeper) then
          write(un,122)  '"qtype" :',       pf%qtype, ','
          write(un,123)  '"nsweeps_pred" :',adjustr(convert_int_array(pf%nsweeps_pred(1:pf%nlevels),pf%nlevels)), ','
          write(un,122)  '"nsweeps_burn" :',pf%nsweeps_burn, ','
          write(un,122)  '"taui0" :',       pf%taui0, ','
       end if
       write(un,124) '"abs_res_tol" :',pf%abs_res_tol, ','
       write(un,124) '"rel_res_tol" :',pf%abs_res_tol, ','
       if(pf%use_sdc_sweeper) then
          write(un,123)  '"use_proper_nodes" :',   convert_logical(pf%use_proper_nodes), ','
          write(un,123)  '"use_composite_nodes" :',convert_logical(pf%use_composite_nodes), ','
          write(un,123)  '"use_no_left_q" :',      convert_logical(pf%use_no_left_q), ','
          write(un,123)  '"PFASST_pred" :',        convert_logical(pf%PFASST_pred), ','
          write(un,123)  '"pipeline_pred" :',      convert_logical(pf%pipeline_pred), ','
          write(un,123)  '"sweep_at_conv" :',      convert_logical(pf%sweep_at_conv), ','
          write(un,123)  '"use_LUq" :',            convert_logical(pf%use_LUq), ','
          write(un,123)  '"use_Sform" :',          convert_logical(pf%use_Sform), ','
          write(un,123)  '"Finterp" :',            convert_logical(pf%Finterp), ','
       end if
       write(un,123)  '"Vcycle" :',             convert_logical(pf%Vcycle), ','
       write(un,123)  '"RK_pred" :',            convert_logical(pf%RK_pred), ','
       write(un,123)  '"save_residuals" :',     convert_logical(pf%save_residuals), ','
       write(un,122)  '"save_timings" :',       pf%save_timings, ','
       write(un,123)  '"save_errors" :',        convert_logical(pf%save_errors), ','
       write(un,123)  '"debug" :',                 convert_logical(pf%debug),','
       write(un,"(A24,A64)")  '"outdir" : ',       adjustr('"'//trim(pf%outdir)//'"')
       write(un,*) '}'
122    FORMAT (A24,I15,A1)
123    FORMAT (A24,A15,A1)
124    FORMAT (A24,e15.6,A1)
       close(unit=un)
    end if
  end subroutine pf_print_options
Call graph
pf_print_options calls convert_logical, pf_stop, convert_int_array