pf_petscVec_create_single – LibPFASST
pf_petscVec_create_single Subroutine
10 statements
Source File
public subroutine pf_petscVec_create_single(this, x, level_index, lev_shape)
Subroutine to create a single array
Arguments
Type Intent Optional Attributes Name
class(pf_petscVec_factory_t), intent(inout) :: this
class(pf_encap_t), intent(inout), allocatable :: x
integer, intent(in) :: level_index
integer, intent(in) :: lev_shape(:)
Calls
Contents
Source Code
pf_petscVec_create_single
Source Code
  subroutine pf_petscVec_create_single(this, x, level_index, lev_shape)
    class(pf_petscVec_factory_t), intent(inout)              :: this
    class(pf_encap_t),      intent(inout), allocatable :: x
    integer,                intent(in   )              :: level_index
    integer,                intent(in   )              :: lev_shape(:)
    integer :: ierr
    allocate(pf_petscVec_t::x,stat=ierr)
    if (ierr /=0) call pf_stop(__FILE__,__LINE__,'allocate fail, error=',ierr)
    call pf_petscVec_build(x, lev_shape)
  end subroutine pf_petscVec_create_single
Call graph
pf_petscvec_create_single calls pf_petscvec_build
pf_petscvec_build calls veccreate, vecgetlocalsize, mpi_comm_rank, vecsetfromoptions, chkerrq