pf_pfasst_run – LibPFASST
pf_pfasst_run Subroutine
35 statements
Source File
public subroutine pf_pfasst_run(pf, q0, dt, tend, nsteps, qend, flags)
This is the main interface to pfasst. It examines the parameters and decides which subroutine to call to execute the code correctly Set the number of time steps to do The user can either pass in the number of time steps or pass in the time step size and length of run Allocate stuff for holding results
deallocate results data
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
The complete PFASST structure
class(pf_encap_t), intent(inout) :: q0
The initial condition
real(kind=pfdp), intent(in) :: dt
The time step for each processor
real(kind=pfdp), intent(in) :: tend
The final time of run
integer, intent(in), optional :: nsteps
The number of time steps
class(pf_encap_t), intent(inout), optional :: qend
The computed solution at tend
integer, intent(in), optional :: flags(:)
User defnined flags
Calls
Contents
Source Code
pf_pfasst_run
Source Code
  subroutine pf_pfasst_run(pf, q0, dt, tend, nsteps, qend, flags)
    type(pf_pfasst_t), intent(inout), target   :: pf   !!  The complete PFASST structure
    class(pf_encap_t), intent(inout   )           :: q0   !!  The initial condition
    real(pfdp),        intent(in   )           :: dt   !!  The time step for each processor
    real(pfdp),        intent(in   )           :: tend !!  The final time of run
    integer,           intent(in   ), optional :: nsteps  !!  The number of time steps
    class(pf_encap_t), intent(inout), optional :: qend    !!  The computed solution at tend
    integer,           intent(in   ), optional :: flags(:)!!  User defnined flags
    !  Local variables
    integer :: nproc  !!  Total number of processors
    integer :: nsteps_loc  !!  local number of time steps
    real(pfdp) :: tend_loc !!  The final time of run
    ! make a local copy of nproc
    nproc = pf%comm%nproc
    !>  Set the number of time steps to do
    !!  The user can either pass in the number of time steps or
    !!  pass in the time step size and length of run
    if (present(nsteps)) then
      nsteps_loc = nsteps
      tend_loc=dble(nsteps_loc*dt)
    else
      nsteps_loc = ceiling(tend/dt)
      !  Do  sanity check on steps
      if (abs(real(nsteps_loc,pfdp)-tend/dt) > dt/100.0) then
        print *,'dt=',dt
        print *,'nsteps=',nsteps_loc
        print *,'tend=',tend
        call pf_stop(__FILE__,__LINE__,'Invalid nsteps=',nsteps)
      end if
    end if
    pf%state%nsteps = nsteps_loc
    !>  Allocate stuff for holding results
    call pf_initialize_results(pf)
    !  do sanity checks on Nproc
    if (mod(nsteps,nproc) > 0) call pf_stop(__FILE__,__LINE__,'nsteps must be multiple of nproc ,nsteps=',nsteps)
    if (present(qend)) then
       call pf_block_run(pf, q0, dt, nsteps_loc,qend=qend,flags=flags)
    else
       call pf_block_run(pf, q0, dt,  nsteps_loc,q0,flags=flags)
    end if
    call pf_dump_results(pf)
    !>   deallocate results data
    call pf_destroy_results(pf)
    !  What we would like to do is check for
    !  1.  nlevels==1  and nprocs ==1 -> Serial SDC
    !      Predictor is either spreadQ or nothing
    !      Then we just call a loop on sweeps
    !      Communication is copy
    !  2.  nlevels > 1  and nprocs ==1 -> Serial MLSDC
    !      Predictor is needed to populate levels (or nothing)
    !      Then we just call a loop on MLSDC sweeps
    !      Communication is copy
    !  3.  nlevels == 1  and nprocs > 1 -> Pipelined SDC
    !      Predictor is just like PFASST, but on finest (only) level (or nothing)
    !  4.  nlevels > 1  and nprocs > 1 -> PFASST
  end subroutine pf_pfasst_run
Call graph
pf_pfasst_run calls pf_block_run, pf_dump_results, pf_stop, pf_destroy_results, pf_initialize_results
pf_block_run calls pf_check_convergence_block, pf_v_cycle, end_timer, call_hooks, start_timer, pf_predictor, pf_broadcast
pf_dump_results calls dump_timings, dump_errors, dump_resids
pf_destroy_results calls destroy_results
pf_initialize_results calls initialize_results
pf_check_convergence_block calls call_hooks, pf_send_status, pf_check_residual
pf_v_cycle calls pf_recv, pf_residual, restrict_time_space_fas, interpolate_time_space, pf_post, pf_send, interpolate_q0
dump_timings calls timer_names
end_timer calls mpi_wtime
call_hooks calls end_timer, start_timer
start_timer calls mpi_wtime
pf_predictor calls end_timer, call_hooks, start_timer, pf_recv, pf_residual, restrict_time_space_fas, interpolate_time_space, pf_send
pf_broadcast calls pf_stop, start_timer, end_timer
pf_recv calls pf_stop, start_timer, end_timer
pf_residual calls end_timer, start_timer, pf_set_resid
restrict_time_space_fas calls end_timer, call_hooks, start_timer, restrict_ts, restrict_ts_integral
pf_send_status calls pf_stop
interpolate_time_space calls end_timer, call_hooks, start_timer, pf_apply_mat
pf_post calls pf_stop
pf_send calls pf_stop, start_timer, end_timer
interpolate_q0 calls end_timer, call_hooks, start_timer
restrict_ts calls pf_apply_mat
restrict_ts_integral calls pf_apply_mat