pf_pfasst_setup – LibPFASST
pf_pfasst_setup Subroutine
28 statements
Source File
public subroutine pf_pfasst_setup(pf)
Setup both the PFASST object and the comm object loop over levels to set parameters Loop over levels setting interpolation and restriction matrices (in time)
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
Main pfasst structure
Calls
Contents
Source Code
pf_pfasst_setup
Source Code
  subroutine pf_pfasst_setup(pf)
    type(pf_pfasst_t), intent(inout), target :: pf   !!  Main pfasst structure
    class(pf_level_t), pointer :: lev_fine, lev_coarse  !!  Pointers to level structures for brevity
    integer                   :: l                      !!  Level loop index
    integer                   :: ierr                   !!  error flag
   !>  loop over levels to set parameters
    do l = 1, pf%nlevels
       call pf_level_setup(pf, pf%levels(l))
    end do
    !>  Loop over levels setting interpolation and restriction matrices (in time)
    do l = pf%nlevels, 2, -1
       lev_fine => pf%levels(l); lev_coarse => pf%levels(l-1)
       allocate(lev_fine%tmat(lev_fine%nnodes,lev_coarse%nnodes),stat=ierr)
       if (ierr /= 0) &
          call pf_stop(__FILE__,__LINE__,"allocate fail",lev_fine%nnodes)
       allocate(lev_fine%rmat(lev_coarse%nnodes,lev_fine%nnodes),stat=ierr)
       if (ierr /= 0) &
          call pf_stop(__FILE__,__LINE__,"allocate fail",lev_fine%nnodes)
       ! with the RK stepper, no need to interpolate and restrict in time
       ! we only copy the first node and last node betweem levels
       if (pf%use_rk_stepper .eqv. .true.) then
          lev_fine%tmat = 0.0_pfdp
          lev_fine%rmat = 0.0_pfdp
          lev_fine%tmat(1,1) = 1.0_pfdp
          lev_fine%tmat(lev_fine%nnodes,lev_coarse%nnodes) = 1.0_pfdp
          lev_fine%rmat(1,1) = 1.0_pfdp
          lev_fine%rmat(lev_coarse%nnodes,lev_fine%nnodes) = 1.0_pfdp
       else         ! else compute the interpolation matrix
          call pf_time_interpolation_matrix(lev_fine%nodes, lev_fine%nnodes, lev_coarse%nodes, lev_coarse%nnodes, lev_fine%tmat)
          call pf_time_interpolation_matrix(lev_coarse%nodes, lev_coarse%nnodes, lev_fine%nodes, lev_fine%nnodes, lev_fine%rmat)
       endif
    end do
  end subroutine pf_pfasst_setup
Call graph
pf_pfasst_setup calls pf_level_setup, pf_time_interpolation_matrix
pf_level_setup calls pf_init_sdcmats
pf_init_sdcmats calls pf_make_matrices, pf_quadrature
pf_make_matrices calls myluq
pf_quadrature calls sdc_qnodes, pf_stop, sdc_qmats
sdc_qnodes calls pf_stop, poly_legendre, poly_diff, poly_roots
myluq calls pf_stop
sdc_qmats calls poly_int, not_proper, poly_eval
poly_roots calls qsort, poly_eval_complex
poly_eval calls poly_eval, poly_eval_complex