pf_petscVec_pack – LibPFASST
pf_petscVec_pack Subroutine
14 statements
Source File
public subroutine pf_petscVec_pack(this, z, flags)
Subroutine to pack an array into a flat array for sending
Arguments
Type Intent Optional Attributes Name
class(pf_petscVec_t), intent(in) :: this
real(kind=pfdp), intent(out) :: z(:)
integer, intent(in), optional :: flags
Calls
Contents
Source Code
pf_petscVec_pack
Source Code
  subroutine pf_petscVec_pack(this, z, flags)
    class(pf_petscVec_t), intent(in   ) :: this
    real(pfdp),     intent(  out) :: z(:)
    integer,     intent(in   ), optional :: flags
    real(pfdp),  pointer :: p_petscVec(:)
    integer :: psize
    call VecGetArrayReadF90(this%petscVec,p_petscVec,this%ierr);CHKERRQ(this%ierr)
    call VecGetLocalSize(this%petscVec,psize,this%ierr);CHKERRQ(this%ierr)
    z=p_petscVec(1:psize)
    call VecRestoreArrayReadF90(this%petscVec,p_petscVec,this%ierr);CHKERRQ(this%ierr)
  end subroutine pf_petscVec_pack
Call graph
pf_petscvec_pack calls chkerrq, vecgetarrayreadf90, vecrestorearrayreadf90, vecgetlocalsize