pf_post – LibPFASST
pf_post Subroutine
25 statements
Source File
public subroutine pf_post(pf, level, tag, direction)
Subroutine to post a receive request for a new initial condition to be received after doing some work
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(in) :: pf
class(pf_level_t), intent(inout) :: level
integer, intent(in) :: tag
integer, intent(in), optional :: direction
Calls
Called by
Contents
Source Code
pf_post
Source Code
  subroutine pf_post(pf, level, tag, direction)
    type(pf_pfasst_t), intent(in)    :: pf
    class(pf_level_t),  intent(inout) :: level
    integer,           intent(in)    :: tag
    integer, optional, intent(in)    :: direction
    integer                          :: dir
    integer ::  ierror , source
    if (pf%comm%nproc .eq. 1) return
    dir = 1 ! default 1: send forward; set to 2 for send backwards
    if(present(direction)) dir = direction
    if (pf%debug) print*,'DEBUG --', pf%rank, 'is beginning pf_post, state%pstatus=', pf%state%pstatus, 'with tag =', tag
    ierror = 0
    if (pf%rank /= 0 .and. pf%state%pstatus == PF_STATUS_ITERATING &
                                  .and. dir == 1) then
       source=pf%rank-1
       call pf%comm%post(pf, level, tag, ierror, source)
    elseif (pf%rank /= pf%comm%nproc-1 .and. pf%state%pstatus == PF_STATUS_ITERATING &
         .and. dir == 2) then
       source=pf%rank+1
       call pf%comm%post(pf, level, tag, ierror, source)
    end if
    if (ierror /= 0) then
       print *, 'Rank',pf%rank
       call pf_stop(__FILE__,__LINE__,'error during post',ierror)
   endif
   if (pf%debug) print*,'DEBUG --', pf%rank, 'is leaving pf_post, state%pstatus=', pf%state%pstatus, 'with tag =', tag
  end subroutine pf_post
Call graph
pf_post calls pf_stop
pf_vcycle calls pf_post
pf_vcycle_pysdc calls pf_post
pf_v_cycle_oc calls pf_post
pf_block_run calls pf_vcycle, pf_vcycle_pysdc
pf_pfasst_block_oc calls pf_v_cycle_oc
pf_pfasst_run calls pf_block_run