pf_parareal_v_cycle – LibPFASST
pf_parareal_v_cycle Subroutine
33 statements
Source File
public subroutine pf_parareal_v_cycle(pf, iteration, t0, dt, level_index_c, level_index_f, flags)
Execute a parareal V-cycle (iteration) It is assumed that we have two levels and two nodes here When this is called the previous coarse integrator result should be stored in Q(1) and the parareal iteration in qend (both on coarse level). If this is called directly after the predictor, these will be the same thing
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
integer, intent(in) :: iteration
real(kind=pfdp), intent(in) :: t0
real(kind=pfdp), intent(in) :: dt
integer, intent(in) :: level_index_c
Coarsest level of V-cycle (not supported)
integer, intent(in) :: level_index_f
Finest level of V-cycle (not supported)
integer, intent(in), optional :: flags
Calls
Called by
Contents
Source Code
pf_parareal_v_cycle
Source Code
  subroutine pf_parareal_v_cycle(pf, iteration, t0, dt,level_index_c,level_index_f, flags)
    type(pf_pfasst_t), intent(inout), target :: pf
    real(pfdp),        intent(in)    :: t0, dt
    integer,           intent(in)    :: iteration
    integer,           intent(in)    :: level_index_c  !! Coarsest level of V-cycle (not supported)
    integer,           intent(in)    :: level_index_f  !! Finest level of V-cycle (not supported)
    integer, optional, intent(in)    :: flags
    type(pf_level_t), pointer :: f_lev, c_lev
    integer :: level_index, j,nsteps_f,nsteps_c
    if (pf%nlevels <2) return     !  This is for two levels only
    c_lev => pf%levels(1)
    f_lev => pf%levels(2)
    nsteps_c= c_lev%ulevel%stepper%nsteps
    nsteps_f= f_lev%ulevel%stepper%nsteps
    !  Save the old value of q0 and qend so that we can compute difference
    call c_lev%delta_q0%copy(f_lev%q0, flags=0) !  Prime the delta_q0 stored in c_lev%delta_q0
    call f_lev%delta_q0%copy(f_lev%qend, flags=0) !  Holding delta_qend in f_lev%delta_q0
    !  Step on fine and store in  fine qend
    level_index=2
    call f_lev%ulevel%stepper%do_n_steps(pf, level_index,pf%state%t0, f_lev%q0,f_lev%qend, dt, nsteps_f)
    !  Subtract the old coarse to get parareal correction  in c_lev%qend
    call f_lev%qend%axpy(-1.0_pfdp,c_lev%Q(1))
    ! Get a new initial condition on fine (will be put in q0)
    call pf_recv(pf, f_lev, 10000+iteration, .true.)
    !  Step on coarse and save in Q(1) for next iteration
    level_index=1
    call c_lev%ulevel%stepper%do_n_steps(pf, level_index,pf%state%t0, f_lev%q0,c_lev%Q(1), dt, nsteps_c)
    !  Finish the parareal update (store in coarse qend) F_old-G_old+G_new
    call f_lev%qend%axpy(1.0_pfdp,c_lev%Q(1))
    !  Send new solution  forward  (nonblocking)
    call pf_send(pf, f_lev, 10000+iteration, .false.)
    !  Complete the delta_q0 on coarse with new initial condition
    call c_lev%delta_q0%axpy(-1.0_pfdp,f_lev%q0, flags=0) !  Complete delta_q0
    !  Complete the jump at the end
    call f_lev%delta_q0%axpy(-1.0_pfdp,f_lev%qend)
    !  Save jumps
    c_lev%max_delta_q0=c_lev%delta_q0%norm(flags=0) ! max jump in q0
    f_lev%residual=f_lev%delta_q0%norm(flags=0)     ! max jump in qend
    call pf_set_resid(pf,1,f_lev%residual)
    call pf_set_resid(pf,2,f_lev%residual)
    call pf_set_delta_q0(pf,1,c_lev%max_delta_q0)
    call pf_set_delta_q0(pf,2,c_lev%max_delta_q0)
  end subroutine pf_parareal_v_cycle
Call graph
pf_parareal_v_cycle calls pf_send, pf_set_resid, pf_set_delta_q0, pf_recv
pf_send calls pf_stop
pf_recv calls pf_start_timer, pf_stop_timer
pf_parareal_block_run calls pf_parareal_v_cycle
pf_parareal_run calls pf_parareal_block_run