pf_parareal_run – LibPFASST
pf_parareal_run Subroutine
34 statements
Source File
public subroutine pf_parareal_run(pf, q0, dt, tend, nsteps, qend)
Do the parareal algorithm Set the number of time steps to do The user can either pass in the number of time steps or pass in the time step size and length of run Allocate stuff for holding results
deallocate results data
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
The complete PFASST structure
class(pf_encap_t), intent(in) :: q0
The initial condition
real(kind=pfdp), intent(in) :: dt
The time step for each processor
real(kind=pfdp), intent(in) :: tend
The final time of run
integer, intent(in), optional :: nsteps
The number of time steps
class(pf_encap_t), intent(inout), optional :: qend
The computed solution at tend
Calls
Contents
Source Code
pf_parareal_run
Source Code
  subroutine pf_parareal_run(pf, q0, dt, tend, nsteps, qend)
    type(pf_pfasst_t), intent(inout), target   :: pf   !!  The complete PFASST structure
    class(pf_encap_t), intent(in   )           :: q0   !!  The initial condition
    real(pfdp),        intent(in   )           :: dt   !!  The time step for each processor
    real(pfdp),        intent(in   )           :: tend !!  The final time of run
    integer,           intent(in   ), optional :: nsteps  !!  The number of time steps
    class(pf_encap_t), intent(inout), optional :: qend    !!  The computed solution at tend
    !  Local variables
    integer :: nproc  !!  Total number of processors
    integer :: nsteps_loc  !!  local number of time steps
    real(pfdp) :: tend_loc !!  The final time of run
    ! make a local copy of nproc
    nproc = pf%comm%nproc
    !>  Set the number of time steps to do
    !!  The user can either pass in the number of time steps or
    !!  pass in the time step size and length of run
    if (present(nsteps)) then
      nsteps_loc = nsteps
      tend_loc=real(nsteps_loc*dt,pfdp)
    else
      nsteps_loc = ceiling(tend/dt)
      !  Do  sanity check on steps
      if (abs(real(nsteps_loc,pfdp)-tend/dt) > dt/1d-7) then
        print *,'dt=',dt
        print *,'nsteps=',nsteps_loc
        print *,'tend=',tend
       call pf_stop(__FILE__,__LINE__,'Invalid nsteps ,nsteps=',nsteps)
      end if
    end if
    pf%state%nsteps = nsteps_loc
    !>  Allocate stuff for holding results
    call pf_initialize_results(pf)
    !  do sanity checks on Nproc
    if (mod(nsteps,nproc) > 0)  call pf_stop(__FILE__,__LINE__,'nsteps must be multiple of nproc ,nsteps=',nsteps)
    if (present(qend)) then
       call pf_parareal_block_run(pf, q0, dt, nsteps_loc,qend=qend)
    else
       call pf_parareal_block_run(pf, q0, dt,  nsteps_loc)
    end if
    call pf_dump_results(pf)
    !>   deallocate results data
    call pf_destroy_results(pf)
  end subroutine pf_parareal_run
Call graph
pf_parareal_run calls pf_dump_results, pf_stop, pf_destroy_results, pf_parareal_block_run, pf_initialize_results
pf_dump_results calls dump_timings, dump_errors, dump_resids
pf_destroy_results calls destroy_results
pf_parareal_block_run calls pf_parareal_predictor, end_timer, call_hooks, start_timer, pf_parareal_v_cycle, pf_check_convergence_block, pf_broadcast
pf_initialize_results calls initialize_results
dump_timings calls timer_names
pf_parareal_predictor calls end_timer, call_hooks, start_timer
end_timer calls mpi_wtime
call_hooks calls end_timer, start_timer
start_timer calls mpi_wtime
pf_parareal_v_cycle calls pf_send, pf_recv, pf_set_resid
pf_check_convergence_block calls call_hooks, pf_check_residual, pf_send_status
pf_broadcast calls pf_stop, start_timer, end_timer
pf_send_status calls pf_stop
pf_send calls pf_stop, start_timer, end_timer
pf_recv calls pf_stop, start_timer, end_timer