pf_parareal_block_run – LibPFASST
pf_parareal_block_run Subroutine
75 statements
Source File
public subroutine pf_parareal_block_run(pf, q0, dt, nsteps, qend, flags)
parareal controller for block mode For initial block, this is done when initial conditions are set When starting a new block, broadcast new initial conditions to all procs Pack away your last solution Everyone resets their q0 Just stick qend in q0 Update the step and t0 variables for new block Call the predictor to get an initial guess on all levels and all processors
Start the parareal iterations
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
class(pf_encap_t), intent(in) :: q0
real(kind=pfdp), intent(in) :: dt
integer, intent(in) :: nsteps
class(pf_encap_t), intent(inout), optional :: qend
integer, intent(in), optional :: flags(:)
Calls
Called by
Contents
Source Code
pf_parareal_block_run
Source Code
  subroutine pf_parareal_block_run(pf, q0, dt, nsteps, qend,flags)
    type(pf_pfasst_t), intent(inout), target   :: pf
    class(pf_encap_t), intent(in   )           :: q0
    real(pfdp),        intent(in   )           :: dt
    integer,           intent(in   )           :: nsteps
    class(pf_encap_t), intent(inout), optional :: qend
    integer,           intent(in   ), optional :: flags(:)
    class(pf_level_t), pointer :: lev  !!  pointer to the one level we are operating on
    integer                   :: j, k
    integer                   :: nblocks !!  The number of blocks of steps to do
    integer                   :: nproc   !!  The number of processors being used
    integer                   :: level_index_c !!  Coarsest level in V (Lambda)-cycle
    integer                   :: level_max_depth !!  Finest level in V-cycle
    integer::  nsteps_c,nsteps_f
    pf%state%dt      = dt
    pf%state%proc    = pf%rank+1
    pf%state%step    = pf%rank
    pf%state%t0      = pf%state%step * dt
    ! set finest level to visit in the following run
    pf%state%finest_level = pf%nlevels
    !  pointer to finest  level to start
    lev => pf%levels(pf%state%finest_level)
    !  Stick the initial condition into q0 (will happen on all processors)
    call lev%q0%copy(q0, flags=0)
    nproc = pf%comm%nproc
    nblocks = nsteps/nproc
    !  Decide what the coarsest level in the V-cycle is
    level_index_c=1
    if (.not. pf%Vcycle)     level_index_c=pf%state%finest_level
    do k = 1, nblocks   !  Loop over blocks of time steps
       if (pf%save_timings > 1) call pf_start_timer(pf, T_BLOCK)
       call call_hooks(pf, -1, PF_PRE_BLOCK)
       ! print *,'Starting  step=',pf%state%step,'  block k=',k
       ! Each block will consist of
       !  1.  predictor
       !  2.  Vcycle until max iterations, or tolerances met
       !  3.  Move solution to next block
       !  Reset some flags
       !>  For initial block, this is done when initial conditions are set
       pf%state%iter    = 0
       pf%state%itcnt   = 0
       pf%state%mysteps = 0
       pf%state%status  = PF_STATUS_PREDICTOR
       pf%state%pstatus = PF_STATUS_PREDICTOR
       pf%comm%statreq  = -66
       pf%state%pfblock = k
       pf%state%sweep = 1   !  Needed for compatibility of residual storage
       if (k > 1) then
          !>  When starting a new block, broadcast new initial conditions to all procs
          if (nproc > 1)  then
             call lev%qend%pack(lev%send)    !!  Pack away your last solution
             call pf_broadcast(pf, lev%send, lev%mpibuflen, pf%comm%nproc-1)
             call lev%q0%unpack(lev%send)    !!  Everyone resets their q0
          else
             call lev%q0%copy(lev%qend, flags=0)    !!  Just stick qend in q0
          end if
          !>  Update the step and t0 variables for new block
          pf%state%step = pf%state%step + pf%comm%nproc
          pf%state%t0   = pf%state%step * dt
       end if
       !> Call the predictor to get an initial guess on all levels and all processors
       call pf_parareal_predictor(pf, pf%state%t0, dt, flags)
       ! After the predictor, the residual and delta_q0 are just zero
       call pf_set_delta_q0(pf,1,0.0_pfdp)
       call pf_set_resid(pf,pf%nlevels,0.0_pfdp)
       call call_hooks(pf, -1, PF_POST_ITERATION)       !  This is the zero iteration
       if (pf%nlevels > 1) then
          !>  Start the parareal iterations
          do j = 1, pf%niters
             call call_hooks(pf, -1, PF_PRE_ITERATION)
             if (pf%save_timings > 1) call pf_start_timer(pf, T_ITERATION)
             pf%state%iter = j
             !  Do a v_cycle
             call pf_parareal_v_cycle(pf, k, pf%state%t0, dt, 1,2)
             !  Check for convergence
             call pf_check_convergence_block(pf, pf%state%finest_level, send_tag=1111*k+j)
             if (pf%save_timings > 1) call pf_stop_timer(pf, T_ITERATION)
             call call_hooks(pf, -1, PF_POST_ITERATION)
             !  If we are converged, exit block
             if (pf%state%status == PF_STATUS_CONVERGED)  then
                call call_hooks(pf, -1, PF_POST_CONVERGENCE)
                call pf_set_iter(pf,j)
                exit
             end if
          end do  !  Loop over j, the iterations in this block
       if (pf%save_timings > 1) call pf_stop_timer(pf, T_BLOCK)
       call call_hooks(pf, -1, PF_POST_BLOCK)
    end if
    end do !  Loop over the blocks
    call call_hooks(pf, -1, PF_POST_ALL)
    !  Grab the last solution for return (if wanted)
    if (present(qend)) then
       call qend%copy(lev%qend, flags=0)
    end if
  end subroutine pf_parareal_block_run
Call graph
pf_parareal_block_run calls pf_parareal_v_cycle, pf_set_resid, call_hooks, pf_parareal_predictor, pf_broadcast, pf_set_delta_q0, pf_check_convergence_block, pf_set_iter
pf_parareal_v_cycle calls pf_set_resid, pf_set_delta_q0, pf_send, pf_recv
pf_parareal_predictor calls call_hooks
pf_broadcast calls pf_stop
pf_check_convergence_block calls call_hooks, pf_send_status, pf_check_residual
pf_send_status calls pf_stop
pf_send calls pf_stop
pf_recv calls pf_start_timer, pf_stop_timer
pf_parareal_run calls pf_parareal_block_run