pf_quadrature – LibPFASST
pf_quadrature Subroutine
55 statements
Source File
public subroutine pf_quadrature(qtype, nnodes, nnodes0, nodes, nflags, Smat, Qmat, proper, composite, no_left)
Subroutine to create quadrature nodes and matrices
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: qtype
integer, intent(in) :: nnodes
integer, intent(in) :: nnodes0
real(kind=pfdp), intent(out) :: nodes(nnodes)
integer, intent(out) :: nflags(nnodes)
real(kind=pfdp), intent(out) :: Smat(nnodes-1,nnodes)
real(kind=pfdp), intent(out) :: Qmat(nnodes-1,nnodes)
logical, intent(in) :: proper
logical, intent(in) :: composite
logical, intent(in) :: no_left
Calls
Called by
Contents
Source Code
pf_quadrature
Source Code
  subroutine pf_quadrature(qtype, nnodes, nnodes0, nodes, nflags, Smat, Qmat,proper,composite,no_left)
    integer,    intent(in)  :: qtype   ! Type of nodes
    integer,    intent(in)  :: nnodes  ! Number of nodes on this level
    integer,    intent(in)  :: nnodes0 ! Number of node on base level (either finest or coarsest)
    real(pfdp), intent(out) :: nodes(nnodes)  !  The nodes
    real(pfdp), intent(out) :: Smat(nnodes-1,nnodes)  !  node to node integration matrix
    real(pfdp), intent(out) :: Qmat(nnodes-1,nnodes)  !  O to node collocation matrix
    integer,    intent(out) :: nflags(nnodes)         !  Flags
    logical,    intent(in)  :: composite  !  Use composite nodes
    logical,    intent(in)  :: proper     !  Use proper nodes instead of node restriction
    logical,    intent(in)  :: no_left    !  Don't use left hand end point
    real(pfdp) :: dt  !  The size of the composite base rule
    real(pfqp) :: qnodes0(nnodes0)  ! quad precision base nodes
    real(pfqp) ::  qnodes(nnodes)   ! quad precision nodes
    real(pfdp) ::  Qmat0(nnodes0-1,nnodes0), Smat0(nnodes0-1,nnodes0),qcomp0(nnodes0-1,nnodes0)
    integer    :: flags0(nnodes0)
    integer :: i,j, ri,rj, refine,m
    Qmat = 0
    Smat = 0
    flags0 = 0
    nflags = 0
    if (composite) then
       ! nodes are given by repeating the coarsest set of nodes.  note
       ! that in this case nnodes0 corresponds to the coarsest number
       ! of nodes.
       refine = (nnodes - 1) / (nnodes0 - 1)
       call sdc_qnodes(qnodes0, flags0, qtype, nnodes0)  !  Make coarsest level nodes
       call sdc_qmats(Qmat0, Smat0, qnodes0, qnodes0, flags0, nnodes0, nnodes0) !  Make coarsest level Qmat
       !  This block matrix will be used to fill in composite Qmat
       do m=1,nnodes0-1
          qcomp0(m,:)=Qmat0(nnodes0-1,:)  !  load each row with the integral over the whole composite step
       end do
       !  Build big block matrix
       dt = 1.0_pfdp / refine
       do i = 1, refine
          ri = (i-1)*(nnodes0-1)+1  !  beginning of ith composite rule
          qnodes(ri:ri+nnodes0-1) = dt * ((i-1) + qnodes0)  !  Assigns endpoints of composites twice, but no biggie
          Smat(ri:ri+nnodes0-2,ri:ri+nnodes0-1) = dt*Smat0   ! Make block diagonal Smat
          Qmat(ri:ri+nnodes0-2,ri:ri+nnodes0-1) = dt*Qmat0  ! Make block diagonal Qmat
          do j = 1, i-1          !   column blocks to left of diag
             rj=(j-1)*(nnodes0-1)+1
             Qmat(ri:ri+nnodes0-2,rj:rj+nnodes0-1) = Qmat(ri:ri+nnodes0-2,rj:rj+nnodes0-1)+ dt*qcomp0
          end do
       end do
    else if (proper) then
       ! nodes are given by proper quadrature rules
       call sdc_qnodes(qnodes, nflags, qtype, nnodes)
       call sdc_Qmats(Qmat, Smat, qnodes, qnodes, nflags, nnodes, nnodes)
    else
       ! nodes are given by refining the finest set of nodes.  note
       ! that in this case nnodes0 corresponds to the finest number of
       ! nodes.
       refine = (nnodes0 - 1) / (nnodes - 1)
       call sdc_qnodes(qnodes0, flags0, qtype, nnodes0)  !  Make finest nodes
       qnodes = qnodes0(::refine)
       nflags = flags0(::refine)
       if (no_left) nflags(1) = 0
       call sdc_Qmats(Qmat, Smat, qnodes, qnodes, nflags, nnodes, nnodes)
    end if
    nodes  = real(qnodes, pfdp)
    if (all(nodes == 0.0d0)) then
       call pf_stop(__FILE__,__LINE__,&
            'ERROR: pf_quadrature: invalid SDC nnodes.')
    end if
  end subroutine pf_quadrature
Call graph
pf_quadrature calls sdc_qnodes, pf_stop, sdc_qmats
sdc_qnodes calls pf_stop, poly_legendre, poly_diff, poly_roots
sdc_qmats calls poly_int, not_proper, poly_eval
poly_roots calls qsort, poly_eval_complex
poly_eval calls poly_eval, poly_eval_complex
pf_init_sdcmats calls pf_quadrature
pf_level_setup calls pf_init_sdcmats
pf_pfasst_setup calls pf_level_setup