pf_recv – LibPFASST
pf_recv Subroutine
55 statements
Source File
public subroutine pf_recv(pf, level, tag, blocking, direction)
Subroutine to recieve the solution from the previous processor
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout) :: pf
type(pf_level_t), intent(inout) :: level
integer, intent(in) :: tag
logical, intent(in) :: blocking
integer, intent(in), optional :: direction
Calls
Called by
Contents
Source Code
pf_recv
Source Code
  subroutine pf_recv(pf, level, tag, blocking, direction)
    type(pf_pfasst_t), intent(inout) :: pf
    type(pf_level_t),  intent(inout) :: level
    integer,           intent(in)    :: tag
    logical,           intent(in)    :: blocking
    integer, optional, intent(in)    :: direction
    integer                          :: dir, ierror,source
    if (pf%comm%nproc .eq. 1) return
    dir = 1 ! default: send forward
    if(present(direction)) dir = direction
    ierror = 0
    if (pf%debug) print*,  'DEBUG --',pf%rank, 'begin recv, tag=',tag,blocking, "pf%state%pstatus=",pf%state%pstatus
    if (pf%rank /= 0 .and. pf%state%pstatus == PF_STATUS_ITERATING &
                                  .and. dir == 1) then
       source=pf%rank-1
       if (pf%save_timings > 1) then
          if (blocking)  then
             call pf_start_timer(pf, T_RECEIVE, level%index)
          else
             call pf_start_timer(pf, T_WAIT, level%index)
          end if
       end if
       call pf%comm%recv(pf, level,tag, blocking, ierror, source)
       if (ierror .ne. 0) call pf_stop(__FILE__,__LINE__,'error during receive, rank=',pf%rank)
       if (pf%save_timings > 1) then
          if (blocking)  then
             call pf_stop_timer(pf, T_RECEIVE, level%index)
          else
             call pf_stop_timer(pf, T_WAIT, level%index)
          end if
       end if
       if (pf%debug) print*,  'DEBUG --',pf%rank, SIZE(level%recv), 'recv buffer=',level%recv
       if (pf%save_timings > 1) call pf_start_timer(pf, T_UNPACK, level%index)
       if (present(direction)) then
          call level%q0%unpack(level%recv, 1)
       else
          call level%q0%unpack(level%recv)
       end if
       if (pf%save_timings > 1) call pf_stop_timer(pf, T_UNPACK, level%index)
    elseif (pf%rank /= pf%comm%nproc-1 .and. pf%state%pstatus == PF_STATUS_ITERATING &
         .and. dir == 2) then
       source=pf%rank+1
       if (pf%save_timings > 1) call pf_start_timer(pf, T_RECEIVE, level%index)
       call pf%comm%recv(pf, level,tag, blocking, ierror, source)
       if (ierror .ne. 0) call pf_stop(__FILE__,__LINE__,'error during receive, rank=',pf%rank)
       if (pf%save_timings > 1) call pf_stop_timer(pf, T_RECEIVE,level%index)
       if (pf%debug) print*,  'DEBUG --',pf%rank, SIZE(level%recv), 'recv buffer=',level%recv
       !  Unpack solution
       if (pf%save_timings > 1) call pf_start_timer(pf, T_UNPACK, level%index)
       if (present(direction)) then
          call level%qend%unpack(level%recv, 2)
       else
          call level%qend%unpack(level%recv)
       end if
       if (pf%save_timings > 1) call pf_stop_timer(pf, T_UNPACK, level%index)
    end if
    if (pf%debug) print*,  'DEBUG --',pf%rank, 'end recv, tag=',tag,blocking
  end subroutine pf_recv
Call graph
pf_recv calls pf_start_timer, pf_stop_timer
pf_v_cycle_oc calls pf_recv
pf_vcycle_pysdc calls pf_recv
pf_parareal_v_cycle calls pf_recv
pf_predictor_oc calls pf_recv
pf_predictor calls pf_recv
pf_vcycle calls pf_recv
pf_block_run calls pf_vcycle_pysdc, pf_predictor, pf_vcycle
pf_parareal_block_run calls pf_parareal_v_cycle
pf_pfasst_block_oc calls pf_v_cycle_oc, pf_predictor_oc
pf_parareal_run calls pf_parareal_block_run
pf_pfasst_run calls pf_block_run