pf_residual – LibPFASST
pf_residual Subroutine
27 statements
Source File
public subroutine pf_residual(pf, level_index, dt, flag)
Compute full residual at each node and measure its size
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
integer, intent(in) :: level_index
real(kind=pfdp), intent(in) :: dt
integer, intent(in), optional :: flag
Calls
Called by
Contents
Source Code
pf_residual
Source Code
  subroutine pf_residual(pf, level_index, dt, flag)
    type(pf_pfasst_t), target,  intent(inout) :: pf
    integer,            intent(in) :: level_index
    real(pfdp),         intent(in)    :: dt
    integer, optional,  intent(in)    :: flag
    real(pfdp) :: res_norms(pf%levels(level_index)%nnodes-1)    !!  Holds norms of residual
    real(pfdp) :: sol_norms(pf%levels(level_index)%nnodes)      !!  Holds norms of solution ! for adjoint: need sol at t0 as well, not only t0+dt
    integer :: m
    type(pf_level_t), pointer   :: lev
    call start_timer(pf, TRESIDUAL)
    lev => pf%levels(level_index)
    call lev%ulevel%sweeper%residual(pf,level_index, dt, flag)
    ! compute max residual norm
    !   sol_norms(1) = lev%Q(1)%norm(flag) ! for adjoint
     sol_norms = lev%Q(1)%norm(flag) ! for adjoint
!    do m = 1, lev%nnodes-1
!       res_norms(m) = lev%R(m)%norm(flag)
       res_norms = lev%R(lev%nnodes-1)%norm(flag)
       !       sol_norms(m+1) = lev%Q(m+1)%norm(flag) ! only the value at lev%nnodes is needed for forward integration, right?
!       sol_norms(m+1) = sol_norms(1) ! only the value at lev%nnodes is needed for forward integration, right?
!    end do
    call end_timer(pf, TRESIDUAL)
    !    lev%residual = res_norms(lev%nnodes-1)
    m = lev%nnodes  ! for usual forward integration
    if(present(flag)) then
      if(flag==2) m = 1
    end if
    lev%residual = maxval(res_norms)
    if (sol_norms(m) > 0.0d0) then
       lev%residual_rel = lev%residual/sol_norms(m)
    else
       lev%residual_rel = 0.0d0
    end if
    call pf_set_resid(pf,lev%index,lev%residual)
!    if (pf%save_residuals .and. pf%state%iter>0)  then
!       pf%results(lev%index)%residuals(pf%state%iter, pf%state%pfblock, pf%state%sweep) = lev%residual
!    end if
!    call end_timer(pf, TRESIDUAL)
  end subroutine pf_residual
Call graph
pf_residual calls start_timer, pf_set_resid, end_timer
start_timer calls mpi_wtime
end_timer calls mpi_wtime
misdcq_sweep calls pf_residual
pf_v_cycle calls pf_residual
pf_predictor_oc calls pf_residual
rk_step calls pf_residual
mkrk_step calls pf_residual
misdcq_oc_sweep calls pf_residual
verlet_sweep calls pf_residual
pf_predictor calls pf_residual
magpicard_sweep calls pf_residual
imex_sweep calls pf_residual
pf_v_cycle_oc calls pf_residual
imk_actually_sweep calls pf_residual
exp_sweep calls pf_residual
imexq_oc_sweep calls pf_residual
pf_block_run calls pf_v_cycle, pf_predictor
pf_pfasst_block_oc calls pf_predictor_oc, pf_v_cycle_oc
imk_sweep calls rk_step, mkrk_step, imk_actually_sweep
pf_pfasst_run calls pf_block_run