pf_stop – LibPFASST
pf_stop Subroutine
13 statements
Source File
public subroutine pf_stop(pf_file, Nline, msg, N)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: pf_file
integer, intent(in) :: Nline
character(len=*), intent(in) :: msg
integer, intent(in), optional :: N
Called by
Contents
Source Code
pf_stop
Source Code
  subroutine pf_stop(pf_file,Nline,msg, N)
    character(len=*), intent(in) :: pf_file
    integer, intent(in):: Nline
    character(len=*), intent(in) :: msg
    integer, intent(in), optional :: N
    print *,'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    print *,'Stopping in File: ', pf_file
    print *,'Line number: ', Nline
    print *,msg
    if (present(N))   print *,'value=',N
    print *,'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    stop
  end subroutine pf_stop
Call graph
pf_quadrature calls pf_stop, sdc_qnodes
ndarray_oc_unpack calls pf_stop
imexq_oc_spreadq0 calls pf_stop
ndarray_axpy calls pf_stop
ndarray_copy calls pf_stop
fftf calls pf_stop
myluq calls pf_stop
fftb calls pf_stop
ndarray_oc_build calls pf_stop
ndarray_oc_destroy_single calls pf_stop
verlet_initialize calls pf_stop
fft_destroy calls pf_stop
ndarray_oc_norm calls pf_stop
pf_pfasst_create calls pf_stop, pf_read_opts
ndarray_oc_copy calls pf_stop
pf_print_options calls pf_stop
get_array1d_oc calls pf_stop
ndarray_oc_setval calls pf_stop
fft_setup calls pf_stop
make_deriv_3d calls pf_stop
ndarray_oc_destroy_array calls pf_stop
ndarray_oc_pack calls pf_stop
misdcq_oc_spreadq0 calls pf_stop
sdc_qnodes calls pf_stop
get_array3d_oc calls pf_stop
ndarray_oc_axpy calls pf_stop
get_array2d_oc calls pf_stop
cast_as_ndarray_oc calls pf_stop
pf_read_opts calls pf_stop
conv_1d calls fftf, fftb
conv_3d calls fftf, fftb
pf_make_matrices calls myluq
conv_2d calls fftf, fftb
ndarray_oc_destroy calls cast_as_ndarray_oc
ndarray_oc_dump_all_hook calls cast_as_ndarray_oc
ndarray_oc_create_single calls ndarray_oc_build
ndarray_oc_dump_hook calls cast_as_ndarray_oc
pf_init_sdcmats calls pf_quadrature, pf_make_matrices
pf_level_setup calls pf_init_sdcmats
pf_pfasst_setup calls pf_level_setup