pf_set_resid – LibPFASST
pf_set_resid Subroutine
9 statements
Source File
public subroutine pf_set_resid(pf, level_index, resid)
Subroutine to store a residual value
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout) :: pf
integer, intent(in) :: level_index
real(kind=pfdp), intent(in) :: resid
Called by
Contents
Source Code
pf_set_resid
Source Code
  subroutine pf_set_resid(pf,level_index,resid)
    type(pf_pfasst_t), intent(inout) :: pf
    integer, intent(in) :: level_index
    real(pfdp), intent(in) :: resid
    !  Make sure indices are valid
    if( min(level_index, pf%state%pfblock,pf%state%iter+1, pf%state%sweep) < 1) return
    if (pf%results%save_residuals)  then
       pf%results%residuals(level_index, pf%state%pfblock,pf%state%iter+1, pf%state%sweep) = resid
    end if
  end subroutine pf_set_resid
Call graph
pf_block_run calls pf_set_resid, pf_vcycle_pysdc, pf_vcycle, pf_predictor
pf_residual calls pf_set_resid
pf_parareal_v_cycle calls pf_set_resid
pf_parareal_block_run calls pf_set_resid, pf_parareal_v_cycle
imexq_oc_sweep calls pf_residual
pf_v_cycle_oc calls pf_residual
pf_vcycle_pysdc calls pf_residual
exp_sweep calls pf_residual
verlet_sweep calls pf_residual
pf_vcycle calls pf_residual
magpicard_sweep calls pf_residual
pf_parareal_run calls pf_parareal_block_run
pf_pfasst_run calls pf_block_run
imex_sweep calls pf_residual
pf_predictor_oc calls pf_residual
mkrk_step calls pf_residual
misdcq_sweep calls pf_residual
pf_predictor calls pf_residual
misdcq_oc_sweep calls pf_residual
imk_actually_sweep calls pf_residual
rk_step calls pf_residual
imk_sweep calls mkrk_step, imk_actually_sweep, rk_step
pf_pfasst_block_oc calls pf_v_cycle_oc, pf_predictor_oc