pf_send_status – LibPFASST
pf_send_status Subroutine
29 statements
Source File
public subroutine pf_send_status(pf, tag, direction)
Subroutine to send this processor's convergence status to the next processor
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout) :: pf
integer, intent(in) :: tag
integer, intent(in), optional :: direction
Calls
Called by
Contents
Source Code
pf_send_status
Source Code
  subroutine pf_send_status(pf, tag, direction)
    type(pf_pfasst_t), intent(inout) :: pf
    integer,           intent(in)    :: tag
    integer, optional, intent(in)    :: direction
    integer ::  dir
    integer ::  istatus
    integer ::  ierror,dest
    if (pf%comm%nproc .eq. 1) return
    dir = 1 ! default 1: send forward; set to 2 for send backwards
    if(present(direction)) dir = direction
    if (pf%rank == 0 .and. dir == 2) return
    if (pf%rank == pf%comm%nproc-1 .and. dir == 1) return
    ierror = 0
    istatus = pf%state%status
    if (dir == 1) then
       dest=pf%rank+1
    elseif (dir == 2) then
       dest=pf%rank-1
    else
      call pf_stop(__FILE__,__LINE__,'invalid dir during send_status',dir)
    end if
    if (pf%debug) print*, 'DEBUG --',pf%rank, 'begins send_status with status', istatus, 'with tag =', tag
    call pf%comm%send_status(pf, tag, istatus, ierror, dest)
    if (pf%debug) print*, 'DEBUG --',pf%rank, 'ends send_status'
    if (ierror /= 0) then
       print *, 'Rank',pf%rank
       call pf_stop(__FILE__,__LINE__,'error during send_status',ierror)
    endif
  end subroutine pf_send_status
Call graph
pf_send_status calls pf_stop
pf_check_convergence_block calls pf_send_status
pf_check_convergence_oc calls pf_send_status
pf_block_run calls pf_check_convergence_block
pf_parareal_block_run calls pf_check_convergence_block
pf_pfasst_block_oc calls pf_check_convergence_oc
pf_parareal_run calls pf_parareal_block_run
pf_pfasst_run calls pf_block_run