pf_set_delta_q0 – LibPFASST
pf_set_delta_q0 Subroutine
9 statements
Source File
public subroutine pf_set_delta_q0(pf, level_index, delta)
Subroutine to store a delta_q0 value
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout) :: pf
integer, intent(in) :: level_index
real(kind=pfdp), intent(in) :: delta
Called by
Contents
Source Code
pf_set_delta_q0
Source Code
  subroutine pf_set_delta_q0(pf,level_index,delta)
    type(pf_pfasst_t), intent(inout)           :: pf
    integer, intent(in) :: level_index
    real(pfdp), intent(in) :: delta
    if( min(level_index, pf%state%pfblock,pf%state%iter+1, pf%state%sweep) < 1) return
    if (pf%results%save_delta_q0)  then
       pf%results%delta_q0(level_index, pf%state%pfblock,pf%state%iter+1, pf%state%sweep) = delta
    end if
  end subroutine pf_set_delta_q0
Call graph
pf_parareal_block_run calls pf_set_delta_q0, pf_parareal_v_cycle
pf_delta_q0 calls pf_set_delta_q0
pf_parareal_v_cycle calls pf_set_delta_q0
pf_parareal_run calls pf_parareal_block_run
pf_vcycle_pysdc calls pf_delta_q0
pf_vcycle calls pf_delta_q0
pf_block_run calls pf_vcycle_pysdc, pf_vcycle
pf_pfasst_run calls pf_block_run