pf_Vcycle – LibPFASST
pf_Vcycle Subroutine
61 statements
Source File
public subroutine pf_Vcycle(pf, iteration, t0, dt, level_index_c, level_index_f, flags)
Execute a Vcycle between levels nfine and ncoarse
Post the nonblocking receives on the all the levels that will be recieving later (for single level this will be skipped) move from fine to coarse doing sweeps
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout), target :: pf
integer, intent(in) :: iteration
real(kind=pfdp), intent(in) :: t0
real(kind=pfdp), intent(in) :: dt
integer, intent(in) :: level_index_c
Coarsest level of Vcycle
integer, intent(in) :: level_index_f
Finest level of Vcycle
integer, intent(in), optional :: flags
Calls
Called by
Contents
Source Code
pf_Vcycle
Source Code
  subroutine pf_Vcycle(pf, iteration, t0, dt,level_index_c,level_index_f, flags)
    type(pf_pfasst_t), intent(inout), target :: pf
    real(pfdp),        intent(in)    :: t0, dt
    integer,           intent(in)    :: iteration
    integer,           intent(in)    :: level_index_c  !! Coarsest level of Vcycle
    integer,           intent(in)    :: level_index_f  !! Finest level of Vcycle
    integer, optional, intent(in)    :: flags
    type(pf_level_t), pointer :: f_lev, c_lev
    integer :: level_index, j
    !>  Post the nonblocking receives on the all the levels that will be recieving later
    !>    (for single level this will be skipped)
    do level_index = level_index_c+1, level_index_f
       f_lev => pf%levels(level_index)
       call pf_post(pf, f_lev, f_lev%index*10000+iteration)
    end do
    !> move from fine to coarse doing sweeps
    do level_index = level_index_f, level_index_c+1, -1
       f_lev => pf%levels(level_index);
       c_lev => pf%levels(level_index-1)
       if (pf%debug) print*,  'DEBUG --',pf%rank,'sweep at beginning of Vycle lev=',level_index
       call f_lev%ulevel%sweeper%sweep(pf, level_index, t0, dt, f_lev%nsweeps)
       call pf_send(pf, f_lev, level_index*10000+iteration, .false.)
       call restrict_time_space_fas(pf, t0, dt, level_index)
       call save(pf,c_lev)
    end do
    ! Do the coarsest level
    level_index=level_index_c
    f_lev => pf%levels(level_index)
    if (pf%pipeline_pred) then
       do j = 1, f_lev%nsweeps
          call f_lev%delta_q0%copy(f_lev%q0)
          call pf_recv(pf, f_lev, f_lev%index*10000+iteration+j, .true.)
          call pf_delta_q0(pf,level_index)
          if (pf%debug) print*,  'DEBUG --',pf%rank,'sweep in mid of Vcycle,lev=',level_index
          call f_lev%ulevel%sweeper%sweep(pf, level_index, t0, dt, 1)
          call pf_send(pf, f_lev, f_lev%index*10000+iteration+j, .false.)
       end do
    else
       call f_lev%delta_q0%copy(f_lev%q0)
       call pf_recv(pf, f_lev, f_lev%index*10000+iteration, .true.)
       call pf_delta_q0(pf,level_index)
       if (pf%debug) print*,  'DEBUG --',pf%rank,'sweep in mid of Vcycle,lev=',level_index
       call f_lev%ulevel%sweeper%sweep(pf, level_index, t0, dt, f_lev%nsweeps)
       call pf_send(pf, f_lev, f_lev%index*10000+iteration, .false.)
    endif
    ! Now move coarse to fine interpolating and sweeping
    do level_index = level_index_c+1,level_index_f
       f_lev => pf%levels(level_index);
       c_lev => pf%levels(level_index-1)
       call interpolate_time_space(pf, t0, dt, level_index, c_lev%Finterp)
       call f_lev%qend%copy(f_lev%Q(f_lev%nnodes), flags=0)
       call f_lev%delta_q0%copy(f_lev%q0)
       call pf_recv(pf, f_lev, level_index*10000+iteration, .false.)   ! This is actually a wait since the receive was posted above
       call pf_delta_q0(pf,level_index)
       if (pf%rank /= 0) then
          ! interpolate increment to q0 -- the fine initial condition
          ! needs the same increment that Q(1) got, but applied to the
          ! new fine initial condition
          call interpolate_q0(pf, f_lev, c_lev,flags=0)
       end if
       ! don't sweep on the finest level since that is only done at beginning
       if (level_index < level_index_f) then
          if (pf%debug) print*,  'DEBUG --',pf%rank,'sweep at end of Vcycle,lev=',level_index
          call f_lev%ulevel%sweeper%sweep(pf, level_index, t0, dt, f_lev%nsweeps)
       else  !  compute residual for diagnostics since we didn't sweep
          pf%state%sweep=1
          call pf_residual(pf, f_lev%index, dt,0)
       end if
    end do
  end subroutine pf_Vcycle
Call graph
pf_vcycle calls interpolate_time_space, restrict_time_space_fas, pf_residual, interpolate_q0, pf_delta_q0, pf_send, pf_post, pf_recv
interpolate_time_space calls pf_apply_mat, call_hooks
restrict_time_space_fas calls restrict_ts, call_hooks, restrict_ts_integral
pf_residual calls pf_set_resid
interpolate_q0 calls call_hooks
pf_delta_q0 calls pf_set_delta_q0
pf_send calls pf_stop
pf_post calls pf_stop
pf_recv calls pf_stop_timer, pf_start_timer
restrict_ts calls pf_apply_mat
restrict_ts_integral calls pf_apply_mat
pf_block_run calls pf_vcycle
pf_pfasst_run calls pf_block_run