poly_eval_complex – LibPFASST
poly_eval_complex Function
10 statements
Source File
public function poly_eval_complex(p, n, x) result(v)
Function to evaluate complex polynomial
Arguments
Type Intent Optional Attributes Name
real(kind=pfqp), intent(in) :: p(0:n)
integer, intent(in), value :: n
complex(kind=pfqp), intent(in) :: x
Return Value complex(kind=pfqp)
Called by
Contents
None
Call graph
poly_eval calls poly_eval_complex, poly_eval
poly_roots calls poly_eval_complex
sdc_qnodes calls poly_roots
pf_quadrature calls sdc_qnodes
pf_init_sdcmats calls pf_quadrature
pf_level_setup calls pf_init_sdcmats
pf_pfasst_setup calls pf_level_setup