restrict_ts_integral – LibPFASST
restrict_ts_integral Subroutine
24 statements
Source File
public subroutine restrict_ts_integral(f_lev_p, c_lev_p, f_encap_array, c_encap_array, f_time, flags)
Restrict (in time and space) f_sol_array to c_sol_array This version is for integrals
Create a temp array for the spatial restriction
Arguments
Type Intent Optional Attributes Name
class(pf_level_t), intent(inout) :: f_lev_p
pointer to fine level
class(pf_level_t), intent(inout) :: c_lev_p
pointer to coarse level
class(pf_encap_t), intent(inout) :: f_encap_array(:)
array of fine level data to be restricted
class(pf_encap_t), intent(inout) :: c_encap_array(:)
array of coarse level data to be computed
real(kind=pfdp), intent(in) :: f_time(:)
time at the fine nodes
integer, intent(in), optional :: flags
Calls
Called by
Contents
Source Code
restrict_ts_integral
Source Code
  subroutine restrict_ts_integral(f_lev_p, c_lev_p, f_encap_array, c_encap_array,f_time, flags)
    !! Restrict (in time and space) f_sol_array  to c_sol_array
    !! This version is for integrals
    class(pf_level_t),  intent(inout) :: f_lev_p   !!   pointer to fine level
    class(pf_level_t),  intent(inout) :: c_lev_p   !!   pointer to coarse level
    class(pf_encap_t),  intent(inout) :: f_encap_array(:)   !! array of fine level data to be restricted
    class(pf_encap_t),  intent(inout) :: c_encap_array(:)   !! array of coarse level data to be computed
    real(pfdp),         intent(in) :: f_time(:)             !! time at the fine nodes
    integer, optional, intent(in)    :: flags
    class(pf_encap_t), allocatable :: f_encap_array_c(:)  !!  fine solution restricted in space only
    integer :: m,j
    integer :: f_nnodes,c_nnodes
    f_nnodes = f_lev_p%nnodes
    c_nnodes = c_lev_p%nnodes
    !!  Create a temp array for the spatial restriction
    call c_lev_p%ulevel%factory%create_array(f_encap_array_c, f_nnodes-1, c_lev_p%index, c_lev_p%shape)
    !  spatial restriction
    do m = 1, f_nnodes-1
       call f_lev_p%ulevel%restrict(f_lev_p, c_lev_p, f_encap_array(m), f_encap_array_c(m), f_time(m), flags)
    end do
    ! temporal restriction
    ! when restricting '0 to node' integral terms, skip the first entry since it is zero
    if (present(flags)) then
       if ((flags .eq. 0) .or. (flags .eq. 1)) &
            call pf_apply_mat(c_encap_array, 1.0_pfdp, f_lev_p%rmat(2:,2:), f_encap_array_c, .true., flags=1)
       if ((flags .eq. 0) .or. (flags .eq. 2)) &
            call pf_apply_mat_backward(c_encap_array, 1.0_pfdp, f_lev_p%rmat(2:,2:), f_encap_array_c, .true., flags=2)
    else
       call pf_apply_mat(c_encap_array, 1.0_pfdp, f_lev_p%rmat(2:,2:), f_encap_array_c, .true.)
    end if
    call c_lev_p%ulevel%factory%destroy_array(f_encap_array_c)
  end subroutine restrict_ts_integral
Call graph
restrict_ts_integral calls pf_apply_mat
restrict_time_space_fas calls restrict_ts_integral
pf_predictor_oc calls restrict_time_space_fas
pf_v_cycle calls restrict_time_space_fas
pf_predictor calls restrict_time_space_fas
pf_v_cycle_oc calls restrict_time_space_fas
pf_block_run calls pf_v_cycle, pf_predictor
pf_pfasst_block_oc calls pf_predictor_oc, pf_v_cycle_oc
pf_pfasst_run calls pf_block_run