restrict_ts – LibPFASST
restrict_ts Subroutine
25 statements
Source File
public subroutine restrict_ts(f_lev, c_lev, f_encap_array, c_encap_array, f_time, flags)
Restrict (in time and space) f_sol_array to c_sol_array This version is for point values (either functions or solutions)
Create a temp array for the spatial restriction
Arguments
Type Intent Optional Attributes Name
class(pf_level_t), intent(inout) :: f_lev
pointer to fine level
class(pf_level_t), intent(inout) :: c_lev
pointer to coarse level
class(pf_encap_t), intent(inout) :: f_encap_array(:)
array of fine level data to be restricted
class(pf_encap_t), intent(inout) :: c_encap_array(:)
array of coarse level data to be computed
real(kind=pfdp), intent(in) :: f_time(:)
time at the fine nodes
integer, intent(in), optional :: flags
Calls
Called by
Contents
Source Code
restrict_ts
Source Code
  subroutine restrict_ts(f_lev, c_lev, f_encap_array, c_encap_array, f_time, flags)
    !! Restrict (in time and space) f_sol_array  to c_sol_array
    !! This version is for point values (either functions or solutions)
    class(pf_level_t),  intent(inout) :: f_lev   !!   pointer to fine level
    class(pf_level_t),  intent(inout) :: c_lev   !!   pointer to coarse level
    class(pf_encap_t),  intent(inout) :: f_encap_array(:)   !! array of fine level data to be restricted
    class(pf_encap_t),  intent(inout) :: c_encap_array(:)   !! array of coarse level data to be computed
    real(pfdp),         intent(in) :: f_time(:)             !! time at the fine nodes
    integer, optional, intent(in)    :: flags
    integer :: m,j
    integer :: f_nnodes,c_nnodes
    f_nnodes = f_lev%nnodes
    c_nnodes = c_lev%nnodes
    !!  Create a temp array for the spatial restriction
    if (f_lev%restrict_workspace_allocated   .eqv. .false.) then
       call c_lev%ulevel%factory%create_array(f_lev%f_encap_array_c, f_nnodes, c_lev%index, c_lev%lev_shape)
       f_lev%restrict_workspace_allocated  = .true.
    end if
    !  spatial restriction
    do m = 1, f_nnodes
       call f_lev%ulevel%restrict(f_lev, c_lev, f_encap_array(m), f_lev%f_encap_array_c(m), f_time(m), flags)
    end do
    ! temporal restriction
    if (present(flags)) then
       if ((flags .eq. 0) .or. (flags .eq. 1)) &
            call pf_apply_mat(c_encap_array, 1.0_pfdp, f_lev%rmat, f_lev%f_encap_array_c, .true., flags)
       if ((flags .eq. 0) .or. (flags .eq. 2)) &
            call pf_apply_mat_backward(c_encap_array, 1.0_pfdp, f_lev%rmat, f_lev%f_encap_array_c, .true., flags=2)
    else
       call pf_apply_mat(c_encap_array, 1.0_pfdp, f_lev%rmat, f_lev%f_encap_array_c, .true.)
    end if
  end subroutine restrict_ts
Call graph
restrict_ts calls pf_apply_mat
restrict_time_space_fas calls restrict_ts
pf_v_cycle_oc calls restrict_time_space_fas
pf_vcycle_pysdc calls restrict_time_space_fas
pf_predictor_oc calls restrict_time_space_fas
pf_predictor calls restrict_time_space_fas
pf_vcycle calls restrict_time_space_fas
pf_block_run calls pf_vcycle_pysdc, pf_predictor, pf_vcycle
pf_pfasst_block_oc calls pf_v_cycle_oc, pf_predictor_oc
pf_pfasst_run calls pf_block_run