start_timer – LibPFASST
start_timer Subroutine
5 statements
Source File
public subroutine start_timer(pf, timer)
Subroutine to start a timer
Arguments
Type Intent Optional Attributes Name
type(pf_pfasst_t), intent(inout) :: pf
integer, intent(in) :: timer
Calls
Called by
Contents
Source Code
start_timer
Source Code
  subroutine start_timer(pf, timer)
    type(pf_pfasst_t), intent(inout) :: pf
    integer,           intent(in)    :: timer
    pf%timers(timer)=MPI_Wtime()
  end subroutine start_timer
Call graph
start_timer calls mpi_wtime
misdcq_oc_sweep calls start_timer, pf_residual, call_hooks
sweep_coupled_implicit_terms calls start_timer
imk_actually_sweep calls start_timer, pf_residual, call_hooks
misdcq_sweep calls start_timer, pf_residual, call_hooks
pf_block_run calls start_timer, pf_predictor, call_hooks, pf_v_cycle, pf_check_convergence_block
pf_parareal_predictor calls start_timer, call_hooks
interpolate_time_space calls start_timer, call_hooks
pf_predictor calls start_timer, interpolate_time_space, pf_residual, restrict_time_space_fas, call_hooks
pf_parareal_block_run calls start_timer, pf_parareal_predictor, call_hooks, pf_check_convergence_block
magpicard_sweep calls start_timer, pf_residual, call_hooks
imex_sweep calls start_timer, pf_residual, call_hooks
interpolate_qend calls start_timer, call_hooks
imexq_oc_sweep calls start_timer, pf_residual, call_hooks
pf_residual calls start_timer
misdc_sweep calls start_timer
verlet_sweep calls start_timer, pf_residual, call_hooks
exp_sweep calls start_timer, pf_residual, call_hooks
pf_predictor_oc calls start_timer, interpolate_time_space, pf_residual, restrict_time_space_fas, call_hooks
amisdc_sweep calls start_timer
restrict_time_space_fas calls start_timer, call_hooks
call_hooks calls start_timer
pf_pfasst_block_oc calls start_timer, pf_predictor_oc, call_hooks, pf_check_convergence_oc, pf_v_cycle_oc
interpolate_q0 calls start_timer, call_hooks
pf_pfasst_run calls pf_block_run
pf_v_cycle calls interpolate_time_space, pf_residual, restrict_time_space_fas, interpolate_q0
pf_check_convergence_block calls call_hooks
rk_step calls pf_residual, call_hooks
pf_parareal_run calls pf_parareal_block_run
mkrk_step calls pf_residual, call_hooks
pf_check_convergence_oc calls call_hooks
imk_sweep calls imk_actually_sweep, rk_step, mkrk_step
pf_v_cycle_oc calls interpolate_time_space, pf_residual, restrict_time_space_fas
amisdcq_sweep calls sweep_coupled_implicit_terms