verlet_sweep – LibPFASST
verlet_sweep Subroutine
85 statements
Source File
public subroutine verlet_sweep(this, pf, level_index, t0, dt, nsweeps, flags)
Uses
pf_mod_timer
pf_mod_hooks
Perform one SDC sweep on level level_index and set qend appropriately Assign level pointer Add the integral term
Add the starting value
Add the dt*v_0
End substep loop
Arguments
Type Intent Optional Attributes Name
class(pf_verlet_t), intent(inout) :: this
Inputs
type(pf_pfasst_t), intent(inout), target :: pf
PFASST structure
integer, intent(in) :: level_index
which level to sweep on
real(kind=pfdp), intent(in) :: t0
Time at beginning of time step
real(kind=pfdp), intent(in) :: dt
time step size
integer, intent(in) :: nsweeps
number of sweeps to do
integer, intent(in), optional :: flags
Calls
Contents
Source Code
verlet_sweep
Source Code
  subroutine verlet_sweep(this, pf, level_index, t0, dt,nsweeps, flags)
    use pf_mod_timer
    use pf_mod_hooks
    !>  Inputs
    class(pf_verlet_t), intent(inout) :: this
    type(pf_pfasst_t), intent(inout),target :: pf    !!  PFASST structure
    integer,           intent(in)    :: level_index  !!  which level to sweep on
    real(pfdp),        intent(in   ) :: t0           !!  Time at beginning of time step
    real(pfdp),        intent(in   ) :: dt           !!  time step size
    integer,           intent(in)    :: nsweeps      !!  number of sweeps to do
    integer, optional, intent(in   ) :: flags
    !>  Local variables
    class(pf_level_t), pointer :: lev    !!  points to current level
    integer     :: k,m, n,nnodes
    real(pfdp)  :: t,dtmhalf,dtsq
    real(pfdp)  :: H
    lev => pf%levels(level_index)   !!  Assign level pointer
    nnodes = lev%nnodes
    !
    ! check hamiltonian
    !
!    call this%hamiltonian(t0+dt, Lev%qend, encapctx%m,H)
!    print *,'Ham=',H,this%Htol,this%H0
!    if ((pf%state%iter > 1) .and. (abs(H-this%H0) < this%Htol)) then
!       call Lev%encap%copy(Lev%qend, Lev%Q(nnodes))
!          print *, 'Skipping SDC sweep'
!       return
!    end if
    !
    ! compute integrals and add fas correction
    !
    dtsq = dt*dt
    do k = 1,nsweeps
       call call_hooks(pf, level_index, PF_PRE_SWEEP)
       if (pf%save_timings > 1) call pf_start_timer(pf, T_SWEEP,level_index)
       pf%state%sweep=k
       do m = 1, lev%nnodes-1
          call lev%I(m)%setval(0.0_pfdp)
          if (pf%state%iter .eq. 1)  then  !  Do verlet on the first iteration
             do n = 1, nnodes
                call lev%I(m)%axpy(dt*this%DQver(m,n), lev%F(n,1),1)
                call lev%I(m)%axpy(dtsq*this%DQQver(m,n), lev%F(n,1),2)
             end do
          else
             do n = 1, nnodes
                call lev%I(m)%axpy(dt*this%DQtil(m,n), lev%F(n,1),1)
                call lev%I(m)%axpy(dtsq*this%DQQtil(m,n), lev%F(n,1),2)
             end do
          end if
          if (level_index < pf%state%finest_level) then
             call lev%I(m)%axpy(1.0_pfdp, lev%tauQ(m))
          end if
       end do
       !  Recompute the first function value if this is first sweep
       if (k .eq. 1) then
          call lev%Q(1)%copy(lev%q0)
          if (pf%save_timings > 1) call pf_start_timer(pf, T_FEVAL,level_index)
          call this%f_eval(lev%Q(1), t0, level_index, lev%F(1,1))
          if (pf%save_timings > 1) call pf_stop_timer(pf, T_FEVAL,level_index)
       end if
       t = t0
       ! do the sub-stepping in sweep
       do m = 1, nnodes-1
          t = t + dt*this%dtsdc(m)
          dtmhalf = 0.5_pfdp*dt*this%dtsdc(m)
          call this%rhs%setval(0.0_pfdp)
          !  Lower triangular verlet to  new piece
          if (pf%state%iter .eq. 1)  then
             do n = 1, m
                call this%rhs%axpy(dtsq*this%QQver(m,n), lev%F(n,1), 2)
             end do
          else
             do n = 1, m
                call this%rhs%axpy(dtsq*this%QQtil(m,n), lev%F(n,1), 2)
             end do
          endif
          !>  Add the integral term
          call this%rhs%axpy(1.0_pfdp, lev%I(m),2)
          !>  Add the starting value
          call this%rhs%axpy(1.0_pfdp, lev%Q(1),2)
          !>  Add the dt*v_0
          call this%rhs%axpy(t-t0, lev%Q(1),12)
          !  Update position term
          call lev%Q(m+1)%copy(this%rhs,2)
          !  update function values
          if (pf%save_timings > 1) call pf_start_timer(pf, T_FEVAL,level_index)
          call this%f_eval(Lev%Q(m+1), t, level_index, Lev%F(m+1,1))
          if (pf%save_timings > 1) call pf_stop_timer(pf, T_FEVAL,level_index)
          !  Now do the v peice
          call this%rhs%setval(0.0_pfdp,1)
          !  Lower triangular verlet to  new piece
          if (pf%state%iter .eq. 1)  then
             do n = 1, m+1
                call this%rhs%axpy(dt*this%Qver(m,n), Lev%F(n,1), 1)
             end do
          else
             do n = 1, m+1
                call this%rhs%axpy(dt*this%Qtil(m,n), Lev%F(n,1), 1)
             end do
          end if
          call this%rhs%axpy(1.0_pfdp,Lev%I(m),1);
          call this%rhs%axpy(1.0_pfdp, Lev%Q(1),1) !  Start m+1 with value from 1
          call lev%Q(m+1)%copy(this%rhs,1)
       end do  !!  End substep loop
       !  Set the value of qend
       !  If Gauss nodes, we must do integration
       !  unless the sweep was an initial Verlet
       !  For Lobatto nodes, we have a choice of whether to just use the
       !  value at the last node, or recompute it.
!       if (this%iqend .and. pf%state%iter .gt. 1) then
!          call Lev%encap%copy(Lev%qend, Lev%Q(1))
!          call Lev%encap%axpy(Lev%qend, dt, Lev%Q(1), 12)  !  Add the dt*v_0 term
!          m = nnodes
!          do n = 1, nnodes
!             call Lev%encap%axpy(Lev%qend, dt*this%Qmat(m,n), Lev%F(n,1),1)
!             call Lev%encap%axpy(Lev%qend, dtsq*this%QQmat(m,n), Lev%F(n,1),2)
!          end do
!          if (associated(Lev%tauQ)) then
!             call Lev%encap%axpy(Lev%qend, 1.0_pfdp, Lev%tauQ(nnodes-1))
!             !          print *,'XXXXXXXXXXX  need code in verlet.f90'
!          end if
!       else
!          call Lev%encap%copy(Lev%qend, Lev%Q(nnodes))
!       end if
       call pf_residual(pf, level_index, dt)
       call lev%qend%copy(lev%Q(lev%nnodes))
       if (pf%save_timings > 1) call pf_stop_timer(pf, T_SWEEP,level_index)
       call call_hooks(pf, level_index, PF_POST_SWEEP)
    end do ! end loop on sweeps
  end subroutine verlet_sweep
Call graph
verlet_sweep calls pf_residual, call_hooks
pf_residual calls pf_set_resid